### ISSUE TITLE
source 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#101]
"source" is an array of type LI_Source.  Definition: "information about the source data used in creating the data specified by the scope."  

Changes:
1. 'description" is a required element of type string.  "description" is required because we are not including "scope" (change 6) in mdJson.
2. "sourceCitation" is an object of type CI_Citation.  This is a name change from "citation" in mdJson 1.0. 
3.  "metadataCitation" is a new array in -1 of type CI_Citation.   Definition: "reference to the metadata for the source."
4. "spatialResolution" is a new object of type "MD_Resolution" in -1.  "spatialResolution" replaces "scaleDenominator" in -2.
5. "referenceSystem" is an object in of type MD_ReferenceSystem (issue #59).  This object was not supported in mdJson 1.0.  Definition: "spatial reference system used by the source."
6. "sourceProcessStep" is an array of type LI_ProcessStep (see issue #62).  "sourceStep" describes the steps taken to acquire and prepare the source resource.  
7. "scope" is a new object in -1 of type MD_Scope (issue #100).  "scope" replaces "sourceExtent" of type EX_Extent in -2.  Note EX_Extent is included in the MD_Scope object.

``` json
{
   "source": [
      {
         "description": "",
         "sourceCitation": {
            "see": "citation 2.0"
         },
         "metadataCitation": [
            {
               "see": "citation 2.0"
            }
         ],
         "spatialResolution": {
            "see": "spatialResolution 2.0"
         },
         "referenceSystem": {
            "see": "spatialReference 2.0"
         },
         "sourceProcessStep": [
            {
               "see": "processStep 2.0"
            }
         ],
         "scope": {
            "see": "scope 2.0"
         }
      }
   ]
}
```

see ISO XML example linage -3.xml

**Comment by jlblcc** [comment]
Changes made:

- renamed sourceCitation to citation
- renamed sourceMetadata to metadataCitation
- renamed sourceReferenceSystem to referenceSystem
- renamed sourceStep to processStep

**Comment by stansmith907** [comment]
I prefer to keep sourceStep rather than changing to processStep.  'sourceStep' are the steps for pre-processing source files rather than a description of the steps taken for the actual lineage.  It is a help to get the mind in the right place.  Similar thinking for sourceReferenceSystem.  This is the resource system for the source which may not be the same as the reference system for the resource.

**Comment by jlblcc** [comment]
I think the use of sourceStep is more confusing, since the object actually is a processStep. When programming against the standard, I would use the same object/class/template for both instances of the object. None of these properties are going to be viewed in isolation, they'll always appear in the context of the containing object. Hence applying the object name, "source" in this case, is redundant.

**Comment by stansmith907** [comment]
I take the opposite view - not always - but here.  This is not a science process step, it is a step taken to obtain and ingest the data into the research; I think there is a real meaningful difference.  

In general I know you like to give object their class name while I like a name that represents their context.

**Comment by jlblcc** [comment]
Call it sourceProcessStep then.

**Comment by stansmith907** [comment]
OK, I'll push it through.

**Comment by stansmith907** [comment]
Replacing "scaleDenominator" with "spatialResolution".
