### ISSUE TITLE
scopeDescription 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#102]
"scopeDescription" is anew array of type MD_ScopeDescription.  Definition: "detailed description/listing of the items specified by the scope".  "scopeDescription must have one and only one of the following attributes.  

Definitions:
- "datasetDescription": "dataset to which the information applies". 
- "attributeDescription": "instances of attribute types to which the information is applied".
- "featureDescription": "instances of feature types to which the information is applied".
- "otherDescription": "class of information that does not fall into the other categories to which the information applies". 

Changes: 
1. "type" is an element of type string.  "type" identifies the selected enumeration.
2. "description" is an element of type string.  "string" is the text of the selected description type.
3. "type" *attribute* and *feature* will not be supported in -2 since their value type is GF_AttributeType documented in ISO 19109 and this XSD is not included in package.

``` json
{
   "scopeDescription": [
      {
         "dataset": "",
         "attributes": "",
         "features": "",
         "other": ""
      }
   ]
}
```

see ISO XML example lineage -3.xml

**Comment by jlblcc** [comment]
I suggest making all the properties singular.

**Comment by stansmith907** [comment]
That's why I did plural.  I'm afraid people will be tempted to place each attribute for a database in separate objects.  When they can list all relevant attributes for a database in one object.  Same for features.

**Comment by jlblcc** [comment]
Well this whole object makes little sense to me, so I'll defer to your interpretation.

**Comment by stansmith907** [comment]
Not saying I would ever use it :)
