### ISSUE TITLE
measure 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#104]
"measure" is an object for associating a number of units with their type.  
1. "type" is an element of type enumeration.  Four types of measurements can be described: distance, length, vertical, and angle. 
2. "value" is an element of type real.  "value" is the number of units in the measurement. 
3. "unitOfMeasure" is an element of type string.  "unitOfMeasure" is the type of units to associate with the "value".

``` json
{
   "measure": [
      {
            "type": "distance|length|vertical|angle",
            "value": 99.9,
            "unitOfMeasure": "unitOfMeasure"
      }
   ]
}
```

**Comment by jlblcc** [comment]
Can this be condensed to an array of objects, like so:
```
{
   "measure": [
      {
            "type": "enum:distance|vertical|angular" 
            "value": 99.9,
            "unitOfMeasure": "unitOfMeasure"
      }
   ]
}
```

**Comment by stansmith907** [comment]
I looked at that.  But this sits inside another enumeration (spatialResolution issue #61) and I thought it might get confusing with types inside of types.  Also remember "measure" is not actually an implemented class.  "distanceMeasure", "verticalMeasure", and "angularMeasure" are all separate classes.  

I could be persuaded to go either way.  Your call.

**Comment by stansmith907** [comment]
Your solution also does not lend itself to implementing a measure type where only one is allowed.

**Comment by jlblcc** [comment]
> I thought it might get confusing with types inside of types. 

Would changing the property names help, i.e. _measureType_.

> Your solution also does not lend itself to implementing a measure type where only one is allowed.

What do you mean? Do you mean that we need to limit the array to one object in some cases?

**Comment by stansmith907** [comment]
> What do you mean? Do you mean that we need to limit the array to one object in some cases?

Yes.  In attributeGroup, and image.  But I was speaking from memory instead of looking.  ISO has the measurement and units in separate fields inline with other elements in those cases, they are not treated as a separate class.  So, I miss-spoke. 

I'm OK with switching this around.  It would just be going back to the way I started.  No problem.  

I will look at replacing the occasions in attribute and image with this new structure when I get to those modules as we could then reuse the component and keep some common patterns.  I'll make the change tonight.
