### ISSUE TITLE
vectorObject 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#106]
"vectorObject" is an array of type MD_GeometryObjects.  Definition: "information about the geometric objects used in the resource".

Changes:
1. "objectType" is a required element of type MD_GeometryObjectTypeCode.  Definition: "name of point or vector objects used to locate zero-, one-, two-, or three-dimensional spatial locations in the resource".
2. "objectCount" is an element of type integer.  Definition: "total number of point or vector objects occurring in the dataset".

``` json
{
   "vectorObject": [
      {
         "objectType": "MD_GeometryObjectTypeCode",
         "objectCount": 0
      }
   ]
}
```

see ISO XML example spatialRepresentation -3.xml

**Comment by dwalt** [comment]
Is this a new element?

**Comment by stansmith907** [comment]
Yes, this is new.  We only handled content type for Grid in mdJson 1.0.  In mdJson 2.0 we handle Grid, Vector, Georeferencable, and Georectified content types.

**Comment by dwalt** [comment]
What is the umbrella class? Can't find grid in old diagram, V14.1

**Comment by stansmith907** [comment]
The parent class is vector representation, and its parent is spatial representation. This is not new to -1 ISO, but it's new to our implementations.
