### ISSUE TITLE
medium 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#108]
"medium" is an object of type MD_Medium.  

Definitions:
1. "mediumSpecification" is an object of type CI_Citation.  Definition: "name of the medium on which the resource can be stored".
2. "density" is a element of type real.  Definition: "density at which the data are recorded".
3. "units" is an element of type string.  Definition: "units of measure for the recording density".
4. "numberOfVolumes" is a new element of type integer.  Definition: "number of items in the media identified".
5. "mediumFormat" is an array of type MD_MediumFormatCode.  Definition: "method used to write to the medium".
6. "note" is an element of type.  Definition: "description of other limitations or requirements for using the medium".
7. "identifier" is an object of MD_Identifier.  Definition: "unique identifier for an instance of the MD_Medium". 

``` json
{
   "medium": [
      {
         "mediumSpecification": {
            "see": "citation 2.0"
         },
         "density": 0.0,
         "units": "",
         "numberOfVolumes": 0,
         "mediumFormat": ["MD_MediumFormatCode"],
         "note": "",
         "identifier": {
            "see": "identifier 2.0"
         }
      }
   ]
}
```

see ISO XML example distribution -3.xml

**Comment by jlblcc** [comment]
Is units still an enum?

**Comment by stansmith907** [comment]
It's free text in ISO.  I placed no restrictions in the mdTranslator.
