### ISSUE TITLE
orderProcess 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#110]
"orderProcess" is an object of type MD_StandardOrderProcess.  Definition: "provides information about how the resource may be obtained, and related instructions and fee information".

Definitions:
1. "fees" is an element of type string which should conform to ISO 4217, but I would not try to enforce that standard.  Definition: "fees and terms for retrieving the resource. Include monetary units".
2. "plannedAvailability" is an element of type DateTime.  Definition: "date and time after which the resource will be available".
3. "orderingInstructions" is an element of type string.  Definition: "general instructions, terms and services provided by the distributor". 
4. "turnaround" is an element of type string.  Definition: "typical turnaround time for the filling of an order".  What do you think about making this type "duration"?

``` json
{
   "orderProcess": [
      {
         "fees": "0.00USD",
         "plannedAvailability": "2016-09-25T00:00:00",
         "orderingInstructions": "",
         "turnaround": ""
      }
   ]
}
```

see ISO XML example distribution -3.xml

**Comment by jlblcc** [comment]
Making turnaround in to duration(#82) seems to make sense to me. Would you just turn it into a text string? Might want to make it an object with a "description" to preserve to original function. At least one would be required.

```json
{
  "duration": "See #82",
  "description": ""
}
```

**Comment by stansmith907** [comment]
We could use duration and turn the result into a string for the ISO output.  But if we do I would drop the "description".  The definition of "turnaround" fits nicely with duration and in cases where someone filled in both duration and description I would be forced to choose "description".

**Comment by jlblcc** [comment]
The problem is someone might need to enter something like "a few weeks". I can set the schema to allow one or the other, or you can just concatenate both together.

**Comment by stansmith907** [comment]
"a few weeks" is 15 days.  Or we don't need duration, just leave it as it is "turnaround". 

I would prefer not creating a new object to handle "turnaround".  Both handle all cases.  Duration is an GML standard and machine readable, "turnaround" is more people readable.  I prefer not doing both.  You can pick one.

**Comment by jlblcc** [comment]
Leave as is.
