### ISSUE TITLE
distributor 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#111]
"distributor" is an array of of type MD_Distributor.  All other resource distribution objects will be accessed through "distributor.  Definition: "provides information about the distributor".

Definitions: 
1. "contact" is a required object of type mdJson "responsibility 2.0" (see issue #52).  Definition: "information about the distributor".
2. "orderProcess" is an array of type MD_StandardOrderProcess (see issue #110).  Definition: "provides information about how the resource may be obtained, and related instructions and fee information".
3. "transferOptions" is an array of type MD_DigitalTransferOptions (see issue #109). Definition: "provides information about the technical means and media used by the distributor".

``` json
{
   "distributor": [
      {
         "contact": {
            "see": "responsibility 2.0"
         },
         "orderProcess": [
            {
               "see": "orderProcess 2.0"
            }
         ],
         "transferOptions": [
            {
               "see": "transferOption 2.0"
            }
         ]
      }
   ]
}
```

see ISO XML example distributor -3.xml

**Comment by dwalt** [comment]
Did distributorFormat go away?

**Comment by jlblcc** [comment]
It's in transferOption (see #109).

**Comment by jlblcc** [comment]
Rename "transferOptions" to "transferOption".
