### ISSUE TITLE
taxonomicClassification 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#113]
"taxonomicClassification" is an object of type TaxonomicClassification.  The element is also renamed in mdJson 2.0 from "taxonClass".  Several of the object's element were also modified.  Definition: "information about the range of taxa addressed in the data set or collection.  NOTE It is recommended that one provide information starting from the taxonomic rank of kingdom, to a level which reflects the data set or collection being documented. The levels of Kingdom, Division/Phylum, Class, Order, Family, Genus, and Species should be included as ranks as appropriate."

Changes:
1. "taxonomicRank" is a required element of type string.  It was renamed in mdJson 2.0 from "taxonRank".  Definition: "name of the taxonomic rank for which the Taxon_Rank_Value is provided. See the example included in the definition of Taxonomic_Classification".
2. "latinName" is a required element of type string.  It was renamed in mdJson 2.0 from "taxonValue".  Definition: "name representing the taxonomic rank of the taxon being described". 
3. "commonName" is an array of type string.  Definition: "specification of applicable common names.  NOTE These common names can be general descriptions of a of organisms if appropriate."
4. "subClassification" is an object of type "taxonomicClassification".  This the recursive part.  
5. "taxonomicSystemId" is an element of type string.  It was added by ADIwg to mdJson 2.0.  Definition: "The ID assigned by the taxonomic system to the 'taxonomicRank'/'latinName' (taxonomic value) of the 'taxonomicClassification' item."

``` json
{
   "taxonomicClassification": {
      "taxonomicSystemId": "",
      "taxonomicRank": "",
      "latinName": "",
      "commonName": [""],
      "subClassification": [
         {
            "see": "taxonomicClassification"
         }
      ]
   }
}
```

see ISO XML example taxonomy -2.xml

**Comment by jlblcc** [comment]
I suggest we add "identifier" to this level. This would help with implementing systems like ITIS which assign an Id to each rank.

**Comment by stansmith907** [comment]
Sounds like a good idea.  I added it to the model and will push it through tomorrow.

**Comment by jlblcc** [comment]
Actually, I was thinking the full "identifier" object.

**Comment by jlblcc** [comment]
Although, I guess the authority could be pulled from  "taxonomicSystem". However, the full identifer would allow for direct linking to related web pages via onlineResource.

**Comment by stansmith907** [comment]
The ID should be from the stated taxonomicSystem.  Allowing a full identifier would allow possible cross system identifiers, plus a lot of extra elements.  Is it going too far?  A simple text field could be either just the ID or a URI.

**Comment by jlblcc** [comment]
Yeah, that may be too much. How about leaving the id as a string and adding an onlineResource array? I would like to be able to link directly to an online reference. I would probably not include the full taxonomic structure and rather link to an online representation like this: https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=180604 or https://www.itis.gov/ITISWebService/jsonservice/getFullHierarchyFromTSN?tsn=558090

**Comment by stansmith907** [comment]
Interesting, but there are no standard metadata formats that will support that.  So your taxonomy would not be searchable through metadata clearinghouses.
