### ISSUE TITLE
address 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#115]
"address".  

Changes:
1. "address" is an array of type CI_Address.  "address" was a single object in mdJson 1.0.
2. "addressType" is a new required array of type "adiwg_addressType".  "adiwg_addressType" is a new codelist included in mdCodes. 
3. "description" is a element of type string.  Definition: "description of the address which may be used to differentiate between multiple addresses.  

``` json
{
   "address": [
      {
         "addressType": [""],
         "description": "",
         "deliveryPoint": [""],
         "city": "",
         "administrativeArea": "",
         "postalCode": "",
         "country": ""
      }
   ],
   "electronicMailAddress": [""]
}
```

see ISO XML example responsibleParty -3.xml

**Comment by stansmith907** [comment]
Now that we allow multiple addresses do we need to include 'type'?

**Comment by jlblcc** [comment]
Probably. Enum?

**Comment by stansmith907** [comment]
Sure ...
- [x] mailing
- [x] physical
- [x] other

Any to add/subtract?

**Comment by stansmith907** [comment]
Think we should build a codelist 'addressType' to use in mdEditor?

**Comment by jlblcc** [comment]
No enum. An array of strings, like phone->service.

**Comment by stansmith907** [comment]
Should we make 'addressType' required or default to ["mailing","physical"]?  I'm thinking make it required.

**Comment by jlblcc** [comment]
Well, I always thought it was weird having e-mail in the same object. Especially with it being increasingly common these days to have entities without an address. We could just wrap all the "address" properties into another, e.g. "location". Could make it an array too so you can associate multiple address with your e-mail at once. That way we can have e-mail without a location(address).

**Comment by stansmith907** [comment]
So, which are you thinking? ...

````json
{
   "address": [
      {
         "addressType": [""],
         "deliveryPoint": [""],
         "city": "",
         "administrativeArea": "",
         "postalCode": "",
         "country": ""
      }
   ],
   "electronicMailAddress": [""],
   
   "location": [
      {
         "address": [
            {
               "addressType": [""],
               "deliveryPoint": [""],
               "city": "",
               "administrativeArea": "",
               "postalCode": "",
               "country": ""
            }
         ],
         "electronicMailAddress": [""]
      }
   ]
}
```` 
How much advantage is there to having multiple email blocks?  I can't see much advantage unless we expand the address block again and make address more like a true location by adding a 'locationName' in additon to 'addressType'.  This would associate email addresses with a location not an address.  Otherwise just more work to collect all the email addresses and decide which to use.  See below ...

````json
{
   "location": [
      {
         "locationName": "",
         "address": [
            {
               "addressType": [""],
               "deliveryPoint": [""],
               "city": "",
               "administrativeArea": "",
               "postalCode": "",
               "country": ""
            }
         ],
         "electronicMailAddress": [""]
      }
   ]
}
````
Is this getting out of control?

**Comment by jlblcc** [comment]
I was actually thinking:

```json
{
  "address": [{
    "location": [{
      "addressType": [""],
      "deliveryPoint": [""],
      "city": "",
      "administrativeArea": "",
      "postalCode": "",
      "country": ""
    }],
    "electronicMailAddress": [""]
  }]
}
```

Just adding the `location[{}] `wrapper.

**Comment by stansmith907** [comment]
In that case I would argue (politely) that 'location' creates multiple addresses for multiple address blocks without distinction to why there are is any difference.  Might as well just go with elevating the 'electronicMailAddress' element to the level of 'address[]' - first example.

**Comment by stansmith907** [comment]
After further discussions (on the phone) we decided elevate 'electronicMailAddress' to the base of 'contact'.  Although it is shown in the model above it is no longer officially part of 'address'.  See 'contact 2.0' issue #48.
