### ISSUE TITLE
date 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#116]
"date"

Changes:
1. "description" is an element of type string.  This was added in mdJson 2.0 to support Arctic LCC and provide additional information about the date.  Definition: "Supplemental information describing the date context.".

``` json
{
   "date": {
      "date": "YYYY-MM-DD",
      "dateType": "CI_DateTypeCode",
      "description": ""
   }
}
```

see ISO XML example citation -3.xml

**Comment by dwalt** [comment]
I'm a little confused why date is an array. Looking at the old class diagram, the calling class may reference it as an array (CI_Citation>gmd:date), but doesn't appear the date class (CI_Date) is an array itself. Is this a change?

**Comment by stansmith907** [comment]
Not a change, just me getting sloppy.  I use the array for testing in all classes.  I forgot to change it back in the issue documentation.  Will fix it.

**Comment by stansmith907** [comment]
Add a "description" element to "date".
