### ISSUE TITLE
geographicExtent 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#118]
"geographicExtent" is a container for the native GeoJSON object we have adopted to describe geographic objects and their extents.  

Definition: 
1. "geoJson" is the native GeoJSON as passed in by the user or prepared by the mdEditor.

``` json
{
   "geographicExtent": [
      {
         "geoJson": []
      }
   ]
}
```

see ISO XML example geographicExtent -3.xml

**Comment by jlblcc** [comment]
Any reason we shouldn't just make _geographicExtent_ an array of geoJSON objects?

**Comment by stansmith907** [comment]
I believe it is. I'll check again when I get to my computer next week. I was attempting to allow arrays of arrays to allow for packaging of geo JSON objects into meaningful groupings.

**Comment by jlblcc** [comment]
Can't the extent itself be used to group geoJSON objects? I think adding the extra _geoJson_ property introduces unnecessary complexity. If you need to group them, just create another extent.

**Comment by stansmith907** [comment]
Each extent can have multiple geographic and other kinds of extents.  Each geographic extent is a collection of GeoJSON objects.  

I fixed the above JSON.  I had made the geographic an object rather than an array.

**Comment by stansmith907** [comment]
Replaced by issue #123
