### ISSUE TITLE
Add computed bounding box

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#120]
Add a computed bounding box to each geometryCollection, feature, featureCollection, and geographicExtent placed into the internal object.  The native GeoJSON will not be modified.  The computed bounding box is in addition to bbox(s) provided in the GeoJSON and will not replace or modify them.

**Comment by jlblcc** [comment]
Should this issue be filed in this repo?

**Comment by stansmith907** [comment]
moved
