### ISSUE TITLE
attributeGroup 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#121]
MD_AttributeGroup is a class array containing multiple attributes belonging to the attribute group.  Definition: "Information about the contentType for groups of attributes for a specific MD_RangeDimension."  The attributes can be expressed as MD_RangeDimension, MD_SampleDimension, MD_Band, or MI_Band.  

Definitions: 
- "attributeContentType" is a required array of type MD_CoverageContentTypeCode.  Definition: "type of information represented by the value(s)".
- "attribute" is an object of elements that comprise a MD_RangeDimension, MD_SampleDimension, MD_Band, or MI_Band class.  Which class will be determined by the writer.

````json
{
   "attributeGroup": [
      {
         "attributeContentType": ["MD_CoverageContentTypeCode"],
         "attribute": [
            {
               "see": "attribute 2.0"
            }
         ]
      }
   ]
}
````

see ISO XML example contentInfo -3.xml

**Comment by jlblcc** [comment]
These properties are in the example, but not referenced above?

```json
      "attribute": [
        {
          "sequenceIdentifier": "sequenceIdentifier0",
          "attributeDescription": "attributeDescription0",
          "sequenceIdentifierType": "sequenceIdentifierType0"
        }
      ]
```

**Comment by jlblcc** [comment]
Ah, see #68

**Comment by stansmith907** [comment]
Right, I should not have included any of the attribute elements in the above example.  Thanks for fixing it.
