### ISSUE TITLE
gmlIdentifier 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#122]
'gmlIdentifier' is included in 'timePeriod' and 'timeInstant' by ISO and was added to 'geometryProperties' by ADIwg.  There are no definitions provided by ISO.  Both properties of 'gmlIdentifier' are required.

````json
{
  "gmlIdentifier": [
    {
      "identifier": "",
      "namespace": ""
    }
  ]
}
````

**Comment by jlblcc** [comment]
I suggest we drop `gmlIdentifier` and use `identifier` instead, see #49. I don't see a good reason to have a separate schema for this. `identifier` only requires the _identifier_ property, the rest is optional and _could_ be provided in this context - it just won't translate in the case of ISO. We could make `namespace` required, although I see no reason to do so in mdJSON.

**Comment by stansmith907** [comment]
I'll need to check this out. ISO identifier has multiple fields that will be presented in cases where showAllTags is true. That will crash validation. Internally I do need both schemas. The schema actually, there is RS_Idenifier as well as MD. We would just be asking users for fields that won't be used, at least by ISO or GeoJSON. So, will would use them?

**Comment by jlblcc** [comment]
If you think it's necessary, we can indicate that some fields won't translate in the description of that schema instance. The different identifier classes are really only used on the ISO(writer) end and can be parsed from a full(or partial) mdJSON identifier object. For my part, when creating the mdJSON, I'd want to use a single identifier class(object) that dumps out from a standard template. If it's not relevant in the translation, it'll just be ignored - which is fine. Like I said, the only required field is identifier.

**Comment by stansmith907** [comment]
Ok, you can close *gmlIdentifier* when you are ready.  I'll remove it as a mdJson class but I do need to keep it as an ISO class.  I can probably also remove it from the internal object.  

MD_Identifier requires identifier
RS_Identifier requires identifier and namespace
GMLIdentifier requires identifier and *should* have namespace.
