### ISSUE TITLE
boundingBox 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#124]
'boundingBox' Definition: "the four side of geodetic box defining the area of the resource".

````json
{
  "boundingBox": {
    "westLongitude": 9.9,
    "eastLongitude": 9.9,
    "southLatitude": 9.9,
    "northLatitude": 9.9
  }
}
````

**Comment by jlblcc** [comment]
Do we want to limit these values to +/-180?

**Comment by stansmith907** [comment]
I can't say for sure it would be helpful in all situations.  However, ISO does require longitudes +/- 180 and latitudes +/- 90.  And since the numbers are latitudes and longitudes (not coordinates) I do think it would be best to restrict the numbers.

**Comment by jlblcc** [comment]
Do we want to do this in the schemas?

**Comment by stansmith907** [comment]
Up to you.  I am checking for this in the mdJson reader module and setting a reader error.  I could also convert longitudes which are +/- 360.  Longitudes beyond that as well as any out of bound latitude should set an error condition.  Should we convert longitudes? or just set an error?
