### ISSUE TITLE
resourceType 2.0

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdJson-schemas#130]
_resourceType_ is an array of objects of type MD_MetadataScope in ISO 19115-1 identifying the kinds and scope of items in the resource.  

- "type" is a required mdJson element of type MD_ScopeCode. Definition: "The type of resource(or component of a resource) being described."
- "name" is an optional field that can be used to distinguish items. Definition: "The name of the resource component."

```json
{
  "resourceType": [
    {
      "type": "MD_ScopeCode",
      "name": ""
    }
  ]
}
```

**Comment by stansmith907** [comment]
Looks good, I'll add it to resourceInfo, additionalResource, and associatedResource.

**Comment by stansmith907** [comment]
Should ressourceType be an array?  It is in ISO.

**Comment by jlblcc** [comment]
Yes, I think so.
