### ISSUE TITLE
resourceTimePeriod

### ISSUE THREAD

**Issue by mmheller** [adiwg/mdJson-schemas#148]
The LCC crosswalk document references resourceInfo > resourceTimePeriod but I cannot find this element.  Should we use resourceInfo > citation > timePeriod instead?

![capture](https://user-images.githubusercontent.com/6976696/28336260-709a5e88-6bbe-11e7-8a7d-674ffdb5d54f.jpg)

**Comment by jlblcc** [comment]
It's actually just timePeriod, http://mdtools.adiwg.org/#viewer-page?v=2-1-5.
