### ISSUE TITLE
Support for Lineage Process Step Source references

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#149]
I believe we (meaning myself) have missed a necessary element in the Lineage < ProcessStep object.  We should add an array to *processStep* to collect *dataSource* used in the process step. I named the array *processSources* in the internal object source and *processSource* in the mdJson schema below:

````ruby
   def newProcessStep
      {
         stepId: nil,
         description: nil,
         rationale: nil,
         timePeriod: {},
         processors: [],
         references: [],
         stepSources: [],
         stepProducts: [],
         scope: {}
      }
   end
````
````json
{
   "processStep": [
      {
         "stepId": "",
         "description": "",
         "rationale": "",
         "timePeriod": {},
         "processor": [],
         "reference": [],
         "stepSource": [],
         "stepProduct": [],
         "scope": {}
      }
   ]
}
````
The contents of processSources would be the existing dataSource object
````ruby
   def newDataSource
      {
         description: nil,
         sourceCitation: {},
         metadataCitation: [],
         spatialResolution: {},
         referenceSystem: {},
         sourceSteps: [],
         scope: {}
      }
   end
````
The mdTranslator tasks are ...
 - [x] internal object
 - [x] mdJson reader
 - [x] html writer
 - [x] mdJson writer
 - [x] 19115 writer
 - [x] add schema tests back after new schema published

**Comment by jlblcc** [comment]
One note: _sourceSteps_ is _sourceProcessStep_ in the schema.

**Comment by stansmith907** [comment]
No problem on the note.  There are some differences in names between the internal and the mdJson schema, this is one of them.

**Comment by stansmith907** [comment]
I changed the design again.  What do you think about having a process step declare it's sources and results separately, i.e. *stepSources* and *stepResults* arrays.  This is more like FGDC than ISO but could easily support both.  If we don't do this we would not be able to reverse to FGDC.

**Comment by jlblcc** [comment]
Is this the right mapping for processStep->source?

            "ISO 19115-2": ["LI_Lineage > source > LI_Source"],
            "FGDC CSDGM": ["dataqual > lineage > srcinfo"]

**Comment by jlblcc** [comment]
Ummmm..what exactly is in stepResults? I don't have that in the schema.

**Comment by stansmith907** [comment]
Neither *stepSource* or *stepResult* are in the schema currently.  I still need to prepare definitions if we choose to implement.  This came up when I started translating FGDC to internal.  I like the FGDC method of lineage description better than ISO.  FGDC places all sources in "FGDC CSDGM": ["dataqual > lineage > srcinfo"] including externally meaningful intermediate data sources created by process steps, similar to our concept of contacts array.  Each source is given an ID.  Then in the process steps "FGDC CSDGM": ["dataqual > lineage > procstep"] the step's sources are mentioned by ID in *srcUsed* and products are mentioned by ID in *srcprod*.  

ISO only maintains these links through the *stepSrc* array (which I forgot to include in the schema) in process step, so intermediate sources get lumped or dumped.  I'm thinking we should keep them separate in mdTranslator and then deal them one way or the other in the writers.  

ISO definition
*stepSrc* - information about the source data used in creating the data specified by the scope.

FGDC definition
*srcUsed* - the Source Citation Abbreviation of a data set used in the processing step.
*srcProd* - the Source Citation Abbreviation of an intermediate data set that (1) is significant in the opinion of the data producer, (2) is generated in the processing step, and (3) is used in later processing steps.

**Comment by stansmith907** [comment]
The mappings are ...

    "ISO 19115-2": DQ_DataQuality < LI_Lineage < LI_ProcessStep < LI_source
    "FGDC CSGDM": dataqual < lineage < procstep < srcused & srcprod

**Comment by stansmith907** [comment]
ISO requirements:

*source* - must have at least 1 [ *description* | *scope* ]
*process* - *description* is required
