### ISSUE TITLE
geographicExtent additional properties 'false'

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#152]
The *additionalProperties* element for *geographicExtent* is set to **false**.  Did we exclude additional elements to this object for some reason?  Or typo?

Schema: 

      "$schema": "http://json-schema.org/draft-04/schema#",
      "id": "geographicExtent.json#",
      "type": "object",
      "description": "Describes the spatial area of the resource",
      "example": "../examples/geographicExtent.json",
      "additionalProperties": false,

Message from validator when *description* element added:

    "The property '#/metadata/resourceInfo/extent/0/geographicExtent/0' contains additional properties ["description"] outside of the schema when none are allowed in schema geographicExtent.json#"

**Comment by jlblcc** [comment]
Yep, that's a bug. Should be set to true.
