### ISSUE TITLE
valueRange new object

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#165]
Schema rules for *valueRange* {object}: "the minimum and maximum values of a continuum of valid
values" 

Rules in attribute:
 - [x] array
 - [x] optional

Element Definitions:
 * minRangeValue: {string} "the least value that the attribute can be assigned"
 * maxRangeValue: {string} "the greatest value that the attribute can be assigned"

Element Rules:
 - [x] minRangeValue required
 - [x] maxRangeValue required

mdJson:
````json
{
   "valueRange": [
      {
         "minRangeValue": "",
         "maxRangeValue": ""
      }
   ]
}
````

FGDC mapping: 
````xml
<metadata>
  <eainfo>
    <detailed>
      <attr>
        <attrdomv>
          <rdom>
            <rdommin>0</rdommin>
            <rdommax>9</rdommax>
            <attrunit>units</attrunit>
            <attrmres>1</attrmres>
          </rdom>
        </attrdomv>
        <attrdomv>
          <rdom>
            <rdommin>A</rdommin>
            <rdommax>F</rdommax>
            <attrunit>grade</attrunit>
            <attrmres>each letter</attrmres>
          </rdom>
        </attrdomv>
      </attr>
    </detailed>
  </eainfo>
</metadata>
````

ISO 19110-2 mapping:
Does not map to ISO 19110

**Comment by jlblcc** [comment]
Can we change the name of this to `valueRange`, or something that is not pluralized? Or is it supposed to be `valueRange`? Example shows `rangeOfValues`.

**Comment by stansmith907** [comment]
I'll change to `valueRange`.  Although *rangeOfValues* is singular, values describing type of range.
