### ISSUE TITLE
check keyword rules

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#173]
*thesaurus* is not required in a keyword set.  However, when *thesaurus* appears as an empty hash it does not pass validation.  Message is "citation is missing title".

**Comment by jlblcc** [comment]
Yep,  thesaurus is a citation- so a title is required. For keyword{} the thesaurus must either be a valid citation or not present. As noted, an empty object is considered invalid.

**Comment by stansmith907** [comment]
Yes, title is required for citation, but citation (thesaurus) is not required for keyword.  The empty thesaurus object  ("thesaurus": {}) is behaving as if a citation is present.  I don't remember us making a rule that empty objects are to behave as loaded objects, but maybe we did.

I checked other tests and empty citation objects are ignored.

**Comment by jlblcc** [comment]
That's just the nature of the schemas. If we have any required properties for an object, an empty object is going to fail validation. In theory, We could write the schemas to allow an empty object, but that would require the `oneOf` construct for every single object in the schemas.

**Comment by stansmith907** [comment]
It is what it is.
