### ISSUE TITLE
gridRepresentation transformationParameterAvailable required

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#187]
Spatial representation > grid representation . transformationParameterAvailable is required.  However, it is Boolean and I default it to 'false'.

**Comment by jlblcc** [comment]
The schema defines the default as false, too. I think we decided that was good enough. If true, where would one obtain the transformationParameters?

**Comment by stansmith907** [comment]
Since the element is Boolean and defaulted to false there is no code change here.  Just  letting people know the parameter will always be written (to ISO anyway).  Maybe this doesn't need to be an mdJson thing.  Also, don't need to know what the parameters are, just if they are available.

**Comment by jlblcc** [comment]
Yeah, I was just curious where one would obtain those parameters. Seems kinda weird to note the availability without providing the info to access the info.
