### ISSUE TITLE
scopeDescription must have ...

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#194]
scopeDescription must have at least one dataset, attribute, feature, or other.

**Comment by stansmith907** [comment]
I don't think this would be breaking since dataset, attribute, feature, and other are the only elements in scopeDescription.  Just adding a check to see that it is not empty.

**Comment by jlblcc** [comment]
I'm going to use `minProperties=1`  instead of requiring one of those properties specifically. That way if someone extends the schema to add another type of scope Description, it won't fail validation. Sound OK?

**Comment by stansmith907** [comment]
Works for me.  That way we can allow user entries.
