### ISSUE TITLE
metadata information dates

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#199]
`metadataDate[]` in the `metadataInfo` section shows [1] in mdTools but is not marked required.  Did we intend to require a metadata creation date?  Should this date be defaulted in when the writer (any writer) generates the record?  

Note: I am not currently requiring creation or any other date in `metadataDate`.

**Comment by jlblcc** [comment]
This is the last discussion, I think.

https://github.com/adiwg/mdJson-schemas/issues/74#issuecomment-276519526

I will remove the minimum requirement,
