### ISSUE TITLE
taxonomy rule change

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#202]
- [x] Rename taxonomic classification `taxonomicRank` to `taxonomicLevel`.
- [x] Rename taxonomic classification `latinName` to `taxonomicName`.
- [x] Change identificationReference to a citation.
- [x] Change taxonomicClassification to an array.

Support deprecated name until version 3.0

**Comment by stansmith907** [comment]
Looks like schema 2.4.9 is requiring `latinName` and `taxonomicRank` even when `taxonomicName` and `taxonomicLevel` are present.  Looking at the 'taxonomy.json' schema it seems correct to me, can you take a look?

**Comment by jlblcc** [comment]
I see the problem. The schema is set to allow either [`latinName` and `taxonomicRank`] or [`taxonomicName` and `taxonomicLevel`]. I will change the `oneOf` to `anyOf`.
