### ISSUE TITLE
New Class - Acquisition

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#212]
Class Definition: __acquisition__
"designations for the measuring instruments, the platform carrying them, and the mission to which the data contributes"

Rules:
 - [ ] optional
---
Element Definitions:
 - [x] scope: { } "the specific data to which the acquisition information applies"
 - [x] plan: [ plan ] "identifies the plan as implemented by the acquisition"
 - [x] requirement: [ requirement ] "identifies the requirement the data acquisition
intends to satisfy"
 - [x] objective: [ objective ] "identification of the area or object to be sensed"
 - [x] platform: [ platform ] "general information about the platform from which the data were taken"
 - [x] instrument: [ instrument ] "general information about the instrument used in data acquisition"
 - [x] operation: [ operation ] "general information about an identifiable activity which provided the data"
 - [x] event: [ event ] "identification of a significant collection point within an operation"
 - [x] pass: [ pass ] "identification of collection coverage"
 - [x] environment: { environment } "a record of the environmental circumstances during the data acquisition"

Rules:
 - [ ] All elements are optional
---
mdJson:
````json
{
   "metadata": {
      "acquisition": [
         {
            "scope": {},
            "plan": [],
            "requirement": [],
            "objective": [],
            "platform": [],
            "instrument": [],
            "operation": [],
            "event": [],
            "pass": [],
            "environment": {}
         }
      ]
   }
}
````
Supports #204

**Comment by hmaier-fws** [comment]
Closed by #307 
Closed by #322
