### ISSUE TITLE
New Class - Environment

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#213]
Class Definition: __environment__
"information about the environmental conditions during the acquisition"

Rules:
 - [ ] optional
---
Element Definitions:
 * averageAirTemperature: (real) "average air temperature along the flight pass during the photo flight"
 * maxRelativeHumidity: (real) "maximum relative humidity along the flight pass during the photo flight"
 * maxAltitude: (real) "maximum altitude during the photo flight"
 * meteorologicalConditions: (character) "meteorological conditions in the photo flight area, in particular clouds, snow and wind"
 * solarAzimuth: (real) "clockwise angle in degrees from north to the centre of the sun’s disc. Note: This angle is calculated from the nadir point of the sensor, not at the centre point of the image"
 * solarElevation: (real) "angle between the horizon and the centre of the Sun’s disk"

Rules:
 - [ ] All elements are optional
---
mdJson:
````json
{
   "acquisition": [
      {
         "environment": {
            "averageAirTemperature": 9.9,
            "maxRelativeHumidity": 9.9,
            "maxAltitude": 9.9,
            "meteorologicalConditions": "meteorological conditions"
            "solarAzimuth": 9.9,
            "solarElevation": 9.9
         }
      }
   ]
}
````

**Comment by dwalt** [comment]
Added "solarAzimuth" and "solarElevation" elements.
