### ISSUE TITLE
New Class - Event

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#214]
Class Definition: __event__
"identification of a significant collection point within an operation"
See: ISO [MI_Event](https://schemas.isotc211.org/19115/-2/mac/2.2.0/mac/#element_MI_Event)

Rules:
 - [ ] optional
---
Element Definitions:
 * eventId: ( character ) "a unique mdJSON system identifier for the event" default: UUID
 * identifier: { identifier } "event name or number"
 * trigger: ( MI_TriggerCode ) "initiator of the event"
 * context: ( MI_ContextCode ) "meaning of the event"
 * sequence: ( MI_SequenceCode ) "relative time ordering of the event"
 * time: ( dateTime ) "time the event occurred"
 * expectedObjective: [ objectiveId ] "objective or objectives satisfied by an event"
 * relatedPass: ( passId ) "pass during which an event occurs"
 * relatedSensor: [ instrumentId ] "instrument or instruments for which the event is meaningful"

Rules:
 - [ ] eventId: required
 - [ ] identifier: required
 - [ ] trigger: required
 - [ ] context: required
 - [ ] sequence: required
 - [ ] time: required
---
mdJson:
````json
{
   "acquisition": [
      {
         "event": [
            {
               "eventId": "event ID",
               "identifier": { },
               "trigger": "MI_TriggerCode",
               "context": "MI_ContextCode",
               "sequence": "MI_SequenceCode",
               "time": "2019-06-10T16:07:00",
               "expectedObjective": ["objectiveId"],
               "relatedPass": "passId",
               "relatedSensor": ["instrumentId"]
            }
         ]
      }
   ]
}
````

**Comment by hmaier-fws** [comment]
Updated definition of eventId to:
eventId: ( character ) "a unique mdJSON system identifier for the event" default: UUID
