### ISSUE TITLE
New Class - Objective

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#216]
Class Definition: __objective__
"describes the characteristics, spatial and temporal extent of the intended object to be observed"
See: ISO [MI_Objective](https://schemas.isotc211.org/19115/-2/mac/2.2.0/mac/#element_MI_Objective)

Rules:
 - [ ] optional
---
Element Definitions:
 * objectiveId: ( character ) "a unique mdJSON system identifier for the objective" default: UUID
 * identifier: [ identifier ] "code used to identify the objective"
 * priority: ( character ) "priority applied to the target"
 * objectiveType: [ MI_ObjectiveTypeCode ] "collection techniques for the objective"
 * function [ character ]: "role or purpose performed by or activity performed at the objective"
 * extent: [ extent ] "extent information including the bounding box, bounding polygon, vertical and temporal extent of the objective"
 * objectiveOccurrence: [ eventId ] "event or events associated with objective completion"
 * pass: [ passId ] "pass of the platform over the objective"
 * sensingInstrument: [ instrumentId ] "instrument which senses the objective data"

Rules:
 - [ ] objectiveId: required
 - [ ] identifier: required

---
mdJson:
````json
{
   "acquisition": [
      {
         "objective": [
            {
               "objectiveId": "objective ID",
               "identifier": [ ],
               "priority": "objective priority",
               "objectiveType": ["MI_ObjectiveTypeCode"],
               "function": ["objective function one"],
               "extent": [ ],
               "objectiveOccurrence": ["eventId"],
               "pass": ["passId"],
               "sensingInstrument": ["instrumentId"]
            }
         ]
      }
   ]
}
````

**Comment by jlblcc** [comment]
Can `objectiveOccurrence` be an empty array? IF so, we shouldn't require it in mdJSON. It can be added in the writer if not present.

**Comment by stansmith907** [comment]
ObjectiveOccurrence is required according to the XSD and ISO 19115-2 documentation.  Mandatory with one or more occurrence.

**Comment by dwalt** [comment]
Added "function" element. Removed objectiveOccurence recommendation as a required element. It is not required according to ISO 19115-1 2019.

**Comment by jwaspin** [comment]
@dwalt or @hmaier-fws Are objectiveOccurrence, pass, and sensingInstrument supposed to be other classes? 
objectiveOccurrence -> [event](https://github.com/adiwg/mdJson-schemas/issues/214)
pass -> [pass](https://github.com/adiwg/mdJson-schemas/issues/220)
sensingInstrument -> [instrument](https://github.com/adiwg/mdJson-schemas/issues/215)

**Comment by dwalt** [comment]
@jwaspin objectiveOccurence is an array of references to Event. Pass is an array of references to PlatformPass. SensingInstrument is an array of references to Instrument. Objective is a parent class to PlatformPass and Instrument. Objective has an associated reference to Event (many to many).

**Comment by hmaier-fws** [comment]
Updated definition of objectiveId to:
objectiveId: ( character ) "a unique mdJSON system identifier for the objective" default: UUID
