### ISSUE TITLE
New Class - Operation

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#217]
Class Definition: __operation__
"designations for the operation used to acquire the dataset"
See: ISO [MI_Operation](https://schemas.isotc211.org/19115/-2/mac/2.2.0/mac/#element_MI_Operation)

Rules:
 - [ ] optional

---
Element Definitions:
 * operationId: ( character ) "a unique mdJSON system identifier for the operation" default: UUID
 * description: ( character ) "description of the mission on which the platform observations are made and the objectives of that mission"
 * citation: { citation } "identification of the mission"
 * identifier: { identifier } "unique identification of the operation"
 * status: ( MD_ProgressCode ) "status of the data acquisition"
 * operationType: ( MI_OperationTypeCode ) "collection technique for the operation"
 * objective: [ objectiveId ] "object(s) or area(s) of interest to be sensed"
 * parentOperation: ( operationId ) "heritage of the operation"
 * childOperation: [ operationId ] "sub-missions that make up part of a larger mission"
 * plan: ( planId ) "plan satisfied by the operation"
 * platform: [ platformId ] "platform (or platforms) used in the operation"
 * significantEvent: [ eventId ] "record of an event occurring during an operation"

Rules:
 - [ ] operationId: required
 - [ ] identifier: required
 - [ ] status: required
 - [ ] parentOperation: required

---
mdJson:
````json
{
   "acquisition": [
      {
         "operation": [
            {
               "operationId": "operation ID",
               "description": "operation description",
               "citation": { },
               "identifier": { },
               "status": "MD_ProgressCode",
               "operationType": "MI_OperationTypeCode",
               "objective": ["objectiveId"],
               "parentOperation": "operationId",
               "childOperation": ["operationId"],
               "plan": "planId",
               "platform": ["platformId"],
               "significantEvent": ["eventId"]
            }
         ]
      }
   ]
}
````

**Comment by jwaspin** [comment]
@dwalt or @hmaier-fws Is platform supposed to be the platform class or is it just a string for the id?
Similar question for significantEvent but I'm not sure what the corresponding class would be.

**Comment by dwalt** [comment]
@jwaspin Platform is a class. Operation is the parent class referencing one or more Platforms associated with an Operation.

**Comment by hmaier-fws** [comment]
Changed definition of operationId to:
operationId: ( character ) "a unique mdJSON system identifier for the operation" default: UUID

**Comment by jwaspin** [comment]
@dwalt @hmaier-fws This says that parentOperation is required. Is that accurate? Isn't there a point at which there is a root/top-level operation that doesn't have a parent?
