### ISSUE TITLE
New Class - Platform

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#219]
Class Definition: __platform__
"designation of the platform used to acquire the dataset"
see: ISO [MI_Platform](https://schemas.isotc211.org/19115/-2/mac/2.2.0/mac/#element_MI_Platform)

Rules:
 - [ ] optional

---
Element Definitions:
 * platformId: ( character ) "a unique mdJSON system identifier for the platform" default: short UUID
 * citation: { citation } "source where information about the platform is described"
 * identifier: { identifier } "unique identification of the platform"
 * description: { character } "narrative description of the platform supporting the instrument"
 * sponsor: [ responsibility ] "organization responsible for building, launch, or operation of the platform"
 * instrument: [ instrumentId ] "instrument(s) mounted on a platform"
 * history: [ instrumentationEventList ] "list of events affecting a platform"

Rules:
 - [ ] platformId: required
 - [ ] identifier: required
 - [ ] description: required
 - [ ] instrument: required

---
mdJson:
````json
{
   "acquisition": [
      {
         "platform": [
            {
               "platformId": "platform ID",
               "citation": { },
               "identifier": { },
               "description": "platform description",
               "sponsor": [ ],
               "instrument": ["instrumentId"],
               "history": [ ]
            }
         ]
      }
   ]
}
````

**Comment by dwalt** [comment]
Added "history" element.

**Comment by jwaspin** [comment]
@dwalt Is this history element the same [instrument event list](https://github.com/adiwg/mdJson-schemas/issues/250) used by the [instrument class](https://github.com/adiwg/mdJson-schemas/issues/215)?

**Comment by dwalt** [comment]
@jwaspin Yes, both Instrument and Platform classes are parent classes. History references one or more InstrumentEventList. Effectively the "history" of events associated with an Instrument or Platform. Platform may be a sensor array in which events are relevant to the array while each sensor in the array may also have its own events.
