### ISSUE TITLE
New Class - Pass

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#220]
Class Definition: __pass__
"identification of collection coverage"
See: ISO [MI_PlatformPass](https://schemas.isotc211.org/19115/-2/mac/2.2.0/mac/#element_MI_PlatformPass)

Rules:
 - [ ] optional

---
Element Definitions:
 * passId: ( character ) "a unique mdJSON system identifier for the pass" default: UUID
 * identifier: { identifier } "unique name of the pass"
 * extent: { GM_Object e.g. polygon, point, linestring, etc. } "area covered by the pass"
 * relatedEvent: [ eventId ] "occurrence of one or more events for a pass"

Rules:
 - [ ] passId: required
 - [ ] identifier: required

---
mdJson:
````json
{
   "acquisition": [
      {
         "pass": [
            {
               "passId": "pass ID",
               "identifier": { },
               "extent": { },
               "relatedEvent": ["eventId"]
            }
         ]
      }
   ]
}
````

**Comment by dwalt** [comment]
Removed "platformId" element. ISO 19115-2 2019 documents do not indicate a direct relationship with the Platform class.

**Comment by hmaier-fws** [comment]
Updated definition of passId to:
passId: ( character ) "a unique **mdJSON system** identifier for the pass" default: UUID


To clarify that this is an internal identifier for use within mdEditor (e.g., as with contacts).
