### ISSUE TITLE
New Class - RequestedDate

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#221]
Class Definition: __requestedDate__
"range of date validity"

Rules:
 - [ ] optional

---
Element Definitions:
 * requestedDateOfCollection: ( dateTime ) "preferred date and time of collection"
 * latestAcceptableDate: ( dateTime ) "latest date and time collection must be completed"

Rules:
 - [ ] requestedDateOfCollection: required
 - [ ] latestAcceptableDate: required

---
mdJson:
````json
{
   "acquisition": [
      {
         "requirement": [
            {
               "requestedDate": {
                  "requestedDateOfCollection": "2019-06-10T16:01:00",
                  "latestAcceptableDate": "2019-06-13:T16:02:00"
               }
            }
         ]
      }
   ]
}
````

**Comment by jwaspin** [comment]
#222
