### ISSUE TITLE
New Class - Requirement

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#222]
Class Definition: __requirement__
"requirement to be satisfied by the planned data acquisition"

Rules:
 - [ ] optional

---
Element Definitions:
 * requirementId: ( character ) "a unique identifier for the requirement" default: short UUID
 * citation: { citation } "identification of reference or guidance material for the requirement"
 * identifier: { identifier } "unique name, or code, for the requirement"
 * requestor: [ responsibility ] "origin of requirement"
 * recipient: [ responsibility ] "person(s), or body(ies), to receive results of requirement"
 * priority: ( MI_PriorityCode ) "relative ordered importance, or urgency, of the requirement"
 * requestedDate: { requestedDate } "required or preferred acquisition date and time"
 * expiryDate: ( dateTime ) "date and time after which collection is no longer valid"
 * satisfiedPlan: [ planId ] "plan that identifies solution to satisfy the requirement"

Rules:
 - [ ] requirementId: required
 - [ ] identifier: required
 - [ ] requestor: required
 - [ ] recipient: required
 - [ ] priority: required
 - [ ] requestedDate: required
 - [ ] expiryDate: required

---
mdJson:
````json
{
   "acquisition": [
      {
         "requirement": [
            {
               "requirementId": "requirement ID",
               "citation": { },
               "identifier": { },
               "requestor": [ ],
               "recipient": [ ],
               "priority": "MI_PriorityCode",
               "requestedDate": { },
               "expiryDate": "2019-06-10T15:50:00",
               "satisfiedPlan": ["planId"]
            }
         ]
      }
   ]
}
````

**Comment by jwaspin** [comment]
#254
