### ISSUE TITLE
New Class - DataQuality

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#223]
Class Definition: __dataQuality__
"quality information for the data specified by a data quality scope"

Rules:
 - [ ] optional

---
Element Definitions:
 * scope: { scope } "The specific data to which the data quality information applies"
 * standaloneQualityReport: { standaloneQualityReport } "Reference to an external standalone quality report"
 * report: [ report ] "aspect of quantitative quality information"

Rules:
 - [ ] scope: required, maximum of one
 - [ ] report: required

---
mdJson:
````json
{
   "metadata": {
      "dataQuality": [
         {
            "scope": { },
            "standaloneQualityReport": { },
            "report": [ ]
         }
      ]
   }
}
````

**Comment by dwalt** [comment]
Updated JSON to reflect stand alone report is not an array, maximum of one allowed.

**Comment by jwaspin** [comment]
@dwalt Since report is required, I assume that is a minimum of 1?

**Comment by dwalt** [comment]
@jwaspin Yes, a minimum of one report is required.
