### ISSUE TITLE
New Class - Report

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#224]
Class Definition: __report__
"Aspect of quantitative quality information"

Rules:
 - [ ] required

---
Element Definitions:
 * type: ( enumerated ) "The type of quality report"
    * Enumerated types supported by XSD
       * DQ_AbsoluteExternalPositionalAccuracy
       * DQ_AccuracyOfATimeMeasurement
       * DQ_ConceptualConsistency
       * DQ_CompletenessCommission
       * DQ_CompletenessOmmission
       * DQ_Confidence
       * DQ_CoverageResult
       * DQ_DomainConsistency
       * DQ_FormatConsistency
       * DQ_GriddedDataPositionalAccuracy
       * DQ_Homogeneity
       * DQ_NonQuantitativeAttributeCorrectness
       * DQ_QuantitativeAttributeAccuracy
       * DQ_RelativeInternalPositionalAccuracy
       * DQ_Representativity
       * DQ_TemporalConsistency
       * DQ_TemporalValidity
       * DQ_ThematicClassisificationCorrectness
       * DQ_TopologicalConsistency
       * DQ_UsibilityElement
    * Additional enumerated types NOT supported by XSD
       * DQ_Completeness
       * DQ_LogicalConsistency
       * DQ_PositioinalAccuracy
       * DQ_TemporalQuality
 * standaloneQualityReportDetails: ( character ) "Clause in the
standaloneQualityReport where this data quality element or any related data quality element (original results in case of derivation or aggregation) is described"
 * qualityMeasure: { qualityMeasure } "Reference to measure used"
 * evaluationMethod: { evaluationMethod } "Evaluation information"
 * quantitativeResult: [ quantitativeResult ] "The values or information about the value(s) (or set of values) obtained from applying a data quality measure"
 * descriptiveResult: [ descriptiveResult ] "Data quality descriptive result"
 * conformanceResult: [ conformanceResult ] "Information about the outcome of evaluating the obtained value (or set of values) against a specified acceptable conformance quality level"
 * coverageResult: [ coverageResult ] "Result of a data quality measure organizing the measured values as a coverage"
 * derivedElementReport: [ report ] "In case of aggregation or derivation, indicates the original element"

Rules:
 - [ ] type: required
 - [ ] report: required
 - [ ] at least one result (quantitativeResult + descriptiveResult + conformanceResult + coverageResult)
 - [ ] derivedElementReport: one and only one required if type = (DQ_Confidence or DQ_Representativity or DQ_Homogeneity)

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "type": "quality report type - enumerated",
               "standaloneQualityReportDetails": "standalone details",
               "qualityMeasure": { },
               "evaluationMethod": { },
               "quantitativeResult": [ ],
               "descriptiveResult": [ ],
               "conformanceResult": [ ],
               "coverageResult": [ ],
               "derivedElementReport": [ ]
            }
         ]
      }
   ]
}
````

**Comment by dwalt** [comment]
Added element "coverageResult". Added definition for element "relatedElementReport".

**Comment by dwalt** [comment]
Removed: relatedElementReport: [ report ] "Information about the reliability of data quality results". While apparent as an association in the ISO UML, I can find no reference in the data dictionary. It appears element association is specific to derivation or aggregation already handled by derivedElementReport.

**Comment by dwalt** [comment]
Added coverageResult to the list of result types as satisfying the minimum one result requirement.

**Comment by jwaspin** [comment]
@dwalt Is the derivedElementReport array still a requirement for this?

**Comment by dwalt** [comment]
@jwaspin Yes. Type is a system field and ADIwg codelist for type of DQ report for use in the UI. standaloneQualityReportDetails is a textual reference to a sub-section within the standAloneReport which describes some aspect of the report in narrative form, for instance, elaborating on how testing methods were applied.
