### ISSUE TITLE
New Class - QualityMeasure

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#225]
Class Definition: __qualityMeasure__
"Reference to the measure used"

Rules:
 - [ ] optional

---
Element Definitions:
 * identifier: { identifier } "Identifier of the measure, value uniquely identifying the measure within a namespace"
 * name: [ character ] "Name of the test applied to the data"
 * description: [ character ] "Description of the measure"

Rules:
 - [ ] name: required if no { identifier }

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "qualityMeasure": {
                  "identifier": { },
                  "name": ["name of measure"],
                  "description": "measure description"
               }
            }
         ]
      }
   ]
}
````

**Comment by jwaspin** [comment]
Class Definition: __qualityMeasure__
"Reference to the measure used"

Rules:
 - [ ] optional

---
Element Definitions:
 * identifier: { identifier } "Identifier of the measure, value uniquely identifying the measure within a namespace"
 * name: [ character ] "Name of the test applied to the data"
 * description: ( character ) "Description of the measure"


Rules:
 - [ ] name: required if no { identifier }
 - [ ] description: required

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "qualityMeasure": {
                  "identifier": { },
                  "name": ["name of measure"],
                  "description": "measure description"
               }
            }
         ]
      }
   ]
}
````

**Comment by hmaier-fws** [comment]
@dwalt the `name` element is currently coded as an array. But it looks like it should just be a character string. See: https://schemas.isotc211.org/19157/-/dqm/1.2.0/

**Comment by hmaier-fws** [comment]
@dwalt  I think I answered my own question. This seems to be [DQ_MeasureReference](https://wiki.esipfed.org/DQ_MeasureReference), which is indeed an array.

https://schemas.isotc211.org/19157/-2/mdq/1.0/dataQualityElement.xsd

**Comment by jwaspin** [comment]
@hmaier-fws Does that mean it's not an array of strings and it's an array of objects instead?

**Comment by hmaier-fws** [comment]
@jwaspin It is an array of character strings. The current version of the schema that is being reviewed is correct.
