### ISSUE TITLE
New Class - EvaluationMethod

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#226]
Class Definition: __evaluationMethod__
"Description of the evaluation method and procedure applied"

Rules:
 - [ ] optional

---
Element Definitions:
 * type: ( enumerated ) "type of evaluation method"
    * Enumerated types supported by XSD
       * DQ_EvaluationMethod
       * DQ_DataInspection
       * DQ_AggregationDerivation
       * DQ_FullInspection
       * DQ_IndirectEvaluation
       * DQ_SampleBasedInspection
 * dateTime: [ dateTime ] "Date or range of dates on which a data quality measure was applied"
 * methodDescription: [ character ] "Description of the evaluation method"
 * evaluationProcedure: { citation } "Reference to the procedure information"
 * referenceDocument: [ citation ] "Information on documents which are referenced in developing and applying a data quality evaluation method"
 * evaluationMethodType: ( DQ_EvaluationMethodTypeCode ) "Type of method used to evaluate quality of the data"
 * deductiveSource: ( character ) "Information on which data are used as sources in deductive evaluation method"
 * samplingScheme: ( character ) "Information of the type of sampling scheme and description of the sampling procedure"
 * lotDescription: ( character ) "Information of how lots are defined"
 * samplingRatio: ( character ) "Information on how many samples on average are extracted for inspection from each lot of population"

Rules:
 - [ ] deductiveSource: required if type [ DQ_IndirectEvaluation ]
 - [ ] samplingScheme: required if type [ DQ_SampleBasedInspection ]
 - [ ] lotDescription: required if type [ DQ_SampleBasedInspection ]
 - [ ] samplingRatio: required if type [ DQ_SampleBasedInspection ]

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "evaluationMethod": {
                  "type": "evaluation method type - enumerated",
                  "dateTime": ["2019-06-11T08:35:00"],
                  "methodDescription": "evaluation method description",
                  "evaluationProcedure": { },
                  "referenceDocument": [ ],
                  "evaluationMethodType": "DQ_EvaluationMethodTypeCode",
                  "deductiveSource": "deductive source",
                  "samplingScheme": "sampling scheme",
                  "lotDescription": "lot description",
                  "samplingRatio": "sampling ratio"
               }
            }
         ]
      }
   ]
}
````

**Comment by jwaspin** [comment]
# Changes

- methodDescription definition
  - [ character ] -> ( character )

# Modified

Class Definition: __evaluationMethod__
"Description of the evaluation method and procedure applied"

Rules:
 - [ ] optional

---
Element Definitions:
 * type: ( enumerated ) "type of evaluation method"
    * Enumerated types supported by XSD
       * DQ_EvaluationMethod
       * DQ_DataInspection
       * DQ_AggregationDerivation
       * DQ_FullInspection
       * DQ_IndirectEvaluation
       * DQ_SampleBasedInspection
 * dateTime: [ dateTime ] "Date or range of dates on which a data quality measure was applied"
 * methodDescription: ( character ) "Description of the evaluation method"
 * evaluationProcedure: { citation } "Reference to the procedure information"
 * referenceDocument: [ citation ] "Information on documents which are referenced in developing and applying a data quality evaluation method"
 * evaluationMethodType: ( DQ_EvaluationMethodTypeCode ) "Type of method used to evaluate quality of the data"
 * deductiveSource: ( character ) "Information on which data are used as sources in deductive evaluation method"
 * samplingScheme: ( character ) "Information of the type of sampling scheme and description of the sampling procedure"
 * lotDescription: ( character ) "Information of how lots are defined"
 * samplingRatio: ( character ) "Information on how many samples on average are extracted for inspection from each lot of population"

Rules:
 - [ ] deductiveSource: required if type [ DQ_IndirectEvaluation ]
 - [ ] samplingScheme: required if type [ DQ_SampleBasedInspection ]
 - [ ] lotDescription: required if type [ DQ_SampleBasedInspection ]
 - [ ] samplingRatio: required if type [ DQ_SampleBasedInspection ]

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "evaluationMethod": {
                  "type": "evaluation method type - enumerated",
                  "dateTime": ["2019-06-11T08:35:00"],
                  "methodDescription": "evaluation method description",
                  "evaluationProcedure": { },
                  "referenceDocument": [ ],
                  "evaluationMethodType": "DQ_EvaluationMethodTypeCode",
                  "deductiveSource": "deductive source",
                  "samplingScheme": "sampling scheme",
                  "lotDescription": "lot description",
                  "samplingRatio": "sampling ratio"
               }
            }
         ]
      }
   ]
}
````
