### ISSUE TITLE
New Class - ConformanceResult

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#227]
Class Definition: __conformanceResult__
"Information about the outcome of evaluating the obtained value (or set of values) against a specified acceptable conformance quality level"

Rules:
 - [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope ) "Scope of the result"
 * specification: { citation ) "Citation of data product specification or user requirement against which data are being evaluated"
 * explanation: ( character ) "Explanation of the meaning of conformance for this result"
 * pass: ( Boolean ) "Indication of the conformance result where 0 = fail and 1 = pass" default: false

Rules:
 - [ ] specification: required 
 - [ ] pass: required 

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "conformanceResult": [
                  {
                     "dateTime": "2019-06-11T09:00:00",
                     "scope": { },
                     "specification": { },
                     "explanation": "conformance result explanation",
                     "pass": false
                  }
               ]
            }
         ]
      }
   ]
}
````

**Comment by jwaspin** [comment]
Class Definition: __conformanceResult__
"Information about the outcome of evaluating the obtained value (or set of values) against a specified acceptable conformance quality level"

Rules:
 - [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope } "Scope of the result"
 * specification: { citation } "Citation of data product specification or user requirement against which data are being evaluated"
 * explanation: ( character ) "Explanation of the meaning of conformance for this result"
 * pass: ( boolean ) "Indication of the conformance result where 0 = fail and 1 = pass" default: false

Rules:
 - [ ] specification: required 
 - [ ] pass: required 

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "conformanceResult": [
                  {
                     "dateTime": [ "2019-06-11T09:00:00" ],
                     "scope": { },
                     "specification": { },
                     "explanation": "conformance result explanation",
                     "pass": false
                  }
               ]
            }
         ]
      }
   ]
}
````
