### ISSUE TITLE
New Class - QuantitativeResult

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#228]
Class Definition: __quantitativeResult__
"The values or information about the value(s) (or set of values) obtained from applying a data quality measure"

Rules:
 - [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope ) "Scope of the result"
 * value: [ real ] "Quantitative value or values, content determined by the evaluation procedure used, accordingly with the value type and valueStructure defined for the measure"
 * valueUnits: ( character ) "Value unit for reporting a data quality result"
 * valueRecordType: ( character ) "Value type for reporting a data quality result, depends of the implementation"

Rules:
 - [ ] value: required 

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "quantitativeResult": [
                  {
                     "dateTime": "2019-06-11T09:00:00",
                     "scope": { },
                     "value": [9.99, 9.0],
                     "valueUnits": "value units",
                     "valueRecordType": "value record type"
                  }
               ]
            }
         ]
      }
   ]
}
````

**Comment by jwaspin** [comment]
Class Definition: __quantitativeResult__
"The values or information about the value(s) (or set of values) obtained from applying a data quality measure"

Rules:
 - [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope } "Scope of the result"
 * value: [ real ] "Quantitative value or values, content determined by the evaluation procedure used, accordingly with the value type and valueStructure defined for the measure"
 * valueUnits: ( character ) "Value unit for reporting a data quality result"
 * valueRecordType: ( character ) "Value type for reporting a data quality result, depends of the implementation"

Rules:
 - [ ] value: required 

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "quantitativeResult": [
                  {
                     "dateTime": [ "2019-06-11T09:00:00" ],
                     "scope": { },
                     "value": [9.99, 9.0],
                     "valueUnits": "value units",
                     "valueRecordType": "value record type"
                  }
               ]
            }
         ]
      }
   ]
}
````
