### ISSUE TITLE
New Class - DescriptiveResult

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#229]
Class Definition: __descriptiveResult__
"Data quality descriptive result"

Rules:
 - [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope ) "Scope of the result"
 * statement: ( character ) "Textual expression of the descriptive result"

Rules:
 - [ ] statement: required 

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "descriptiveResult": [
                  {
                     "dateTime": "2019-06-11T09:00:00",
                     "scope": { },
                     "statement": "descriptive result statement"
                  }
               ]
            }
         ]
      }
   ]
}
````

**Comment by jwaspin** [comment]
@dwalt 

Some of the dateTimes are arrays and some are just single strings. In this case the element definition differs from the example. Can you confirm for all of the different data quality components whether or not the dateTime should be an array of dateTime strings or if it should be a single string? Or does it depend on the specific component as to what it should be?

**Comment by jwaspin** [comment]
Class Definition: __descriptiveResult__
"Data quality descriptive result"

Rules:
 - [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope } "Scope of the result"
 * statement: ( character ) "Textual expression of the descriptive result"

Rules:
 - [ ] statement: required 

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "descriptiveResult": [
                  {
                     "dateTime": [ "2019-06-11T09:00:00" ],
                     "scope": { },
                     "statement": "descriptive result statement"
                  }
               ]
            }
         ]
      }
   ]
}
````
