### ISSUE TITLE
New Class - StandaloneQualityReport

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#230]
Class Definition: __standaloneQualityReport__
"Reference to an external standalone quality report"

Rules:
 - [ ] optional

---
Element Definitions:
 * reportReference: { citation } "Reference to the associated standalone quality report"
 * abstract: ( character ) "Abstract for the associated standalone quality report"

Rules:
 - [ ] reportReference: required, maximum of one
 - [ ] abstract: required, maximum of one

---
mdJson:
````json
{
   "dataQuality": [
      {
         "standaloneQualityReport": {
            "reportReference": { },
            "abstract": "stand alone abstract"
         }
      }
   ]
}
````

**Comment by dwalt** [comment]
Added definition for elementReport.

**Comment by dwalt** [comment]
Updated element rules to identify maximum occurrences of 1.

**Comment by dwalt** [comment]
Removed standard report references. Not supported by ISO 19157. References are from standard reports to a clause within a standAloneReport that further elucidates information regarding that report, through an internal document reference, such as a paragraph reference.
