### ISSUE TITLE
Add Scope to Spatial Representation

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdJson-schemas#245]
Add MD_scope to spatialRepresentation

resourceInfo{}*>spatialRepresentation[]>scope{}
Note: scope includes scopeCode, description and extent which are needed to clarify for which resource objects the spatial representation is for

Related issue:
mdTranslator: https://github.com/adiwg/mdTranslator/issues/222
mdEditor: https://github.com/adiwg/mdEditor/issues/103

**Comment by hmaier-fws** [comment]
closed by PR #258
