### ISSUE TITLE
New Class - InstrumentationEvent

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdJson-schemas#251]
Class Definition: instrumentationEvent
"an event related to a platform, instrument, sensor"

Rules:
- [ ] Optional

---
Element Definitions:
* citation: [ citation ] "citation to the instrumentationEvent"
* description: { character } "description of the instrumentationEvent"
* extent: [ extent ] "extent of the instrumentationEvent"
* type: { eventType } "type of the instrumentationEvent"
* revisionHistory: [ revision ] "history of revisions to the instrumentationEvent"

Rules:
- [ ] description: required
- [ ] type: required

---
mdJSON
````json
"instrumentationEventList": [
  {
      "instrumentationEvent": 
          {
              "citation": [ ],
              "description": { },
              "extent": [ ],
               "eventType": { },
               "revisionHistory": [ ]
            }
   }
]

**Comment by jwaspin** [comment]
@dwalt It looks like description is supposed to be a string not an object, just want to confirm that's correct

**Comment by dwalt** [comment]
@jwaspin Yes, it is a string.

**Comment by jwaspin** [comment]
https://github.com/adiwg/mdJson-schemas/issues/250
