### ISSUE TITLE
New Class - CoverageResult

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdJson-schemas#255]
Class Definition: CoverageResult
"Result of  data quality measure organizing the measured values as a coverage"

Rules:

- [ ] optional

---
Element Definitions:
 * dateTime: ( dateTime ) "Date when the result was generated"
 * scope: ( scope ) "Scope of the result"
 * spatialRepresentationType: ( spatialRepresentationType ) "Method used to spatially represent the coverage result"
 * spatialRepresentation: ( spatialRepresentation ) "Provides the digital representation of data quality measures composing the coverage result"
 * resultContent: ( rangeDimension ) "Provides the description of the content of the result coverage when the quality coverage is included with the resource being described. i.e. semantic definition of the data quality measures"
 * resourceFormat: ( format ) "Provides information about the format of the result coverage data"
 * resultFile: ( dataFile ) "Provides information about the data file containing the result coverage data"
 
Rules:
 - [ ] scope: maximum one
 - [ ] spatialRepresentationType: required, maximum one
 - [ ] spatialRepresentation: required, maximum one
 - [ ] resultContent: required if resourceFormat is null and resultFile is null
 - [ ] resourceFormat:  required if resultContent is null, maximum one
 - [ ] resultFile: required if resultContent is null, maximum one
 
---
mdJson: **See [comment below](https://github.com/adiwg/mdJson-schemas/issues/255#issuecomment-1876176119) for updated schema**
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "coverageResult": [
                  {
                     "dateTime": "2019-06-11T09:00:00",
                     "scope": { },
                     "spatialRepresentationType": { },
                     "spatialRepresentation":  { },
                     "resultContent": [ ],
                     "resourceFormat": { },
                     "resultFile": { }
                  }
               ]
            }
         ]
      }
   ]
}
````

**Comment by dwalt** [comment]
Refactored element names from ISO 19157 2018 amendment names to generic names in alignment with existing mdJSON elements.

**Comment by dwalt** [comment]
Reconsidered element names and returned to 2018 naming for resultContent and resultFile. Changed associative element classes for resultContent and resultFile to correct previous mapping errors.

**Comment by jwaspin** [comment]
@dwalt Is this task completed? It looks to be part of data quality and it looks like it's in the schema viewer but not necessarily fully defined.

**Comment by jwaspin** [comment]
@dwalt 

Is spatialRepresentationType supposed to be an object or a string?

Is resultFile supposed to be an object or a string?

If these are objects there's no indication what type of object to use for them. I noticed resourceFormat was set to a string, so I switched it to be a `format` object, I assume that's correct.

**Comment by jwaspin** [comment]
Class Definition: CoverageResult
"Result of  data quality measure organizing the measured values as a coverage"

Rules:

- [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope } "Scope of the result"
 * spatialRepresentationType: ( enumerated ) "Method used to spatially represent the coverage result"
   * Enumerated types supported by XSD
     * DQ_
 * spatialRepresentation: { spatialRepresentation } "Provides the digital representation of data quality measures composing the coverage result"
 * resultContent: [ rangeDimension ] "Provides the description of the content of the result coverage when the quality coverage is included with the resource being described. i.e. semantic definition of the data quality measures"
 * resourceFormat: ( enumerated ) "Provides information about the format of the result coverage data"
 * resultFile: ( character ) "Provides information about the data file containing the result coverage data"
 
Rules:
 - [ ] scope: maximum one
 - [ ] spatialRepresentationType: required, maximum one
 - [ ] spatialRepresentation: required, maximum one
 - [ ] resultContent: required if resourceFormat is null and resultFile is null
 - [ ] resourceFormat:  required if resultContent is null, maximum one
 - [ ] resultFile: required if resultContent is null, maximum one
 
---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "coverageResult": [
                  {
                     "dateTime": [ "2019-06-11T09:00:00" ],
                     "scope": { },
                     "spatialRepresentationType": "spatial representation type - enumerated",
                     "spatialRepresentation":  { },
                     "resultContent": [ ],
                     "resourceFormat": "resource format - enumerated",
                     "resultFile": "url"
                  }
               ]
            }
         ]
      }
   ]
}
````

**Comment by jwaspin** [comment]
# Changes

- Definitions
  - Updated to show object types with { } 
  - Renamed resultContent --> resultContentDescription and noted it as the MD_CoverageDescription object
  - Changed dateFile --> qualityResultFile for more accurate name
- Examples
  - Changed resultContentDescription from array to object

### Additional Notes

The resultFile is the [mdq:QualityResultFile](https://wiki.esipfed.org/QualityResultFile)

These changes are based on [this coverage result information.](https://wiki.esipfed.org/QE_CoverageResult)

# Modified

Class Definition: CoverageResult
"Result of  data quality measure organizing the measured values as a coverage"

Rules:

- [ ] optional

---
Element Definitions:
 * dateTime: ( dateTime ) "Date when the result was generated"
 * scope: { scope } "Scope of the result"
 * spatialRepresentationType: ( spatialRepresentationType ) "Method used to spatially represent the coverage result"
 * spatialRepresentation: { spatialRepresentation } "Provides the digital representation of data quality measures composing the coverage result"
 * resultContentDescription: { MD_CoverageDescription } "Provides the description of the content of the result coverage when the quality coverage is included with the resource being described. i.e. semantic definition of the data quality measures"
 * resourceFormat: { format } "Provides information about the format of the result coverage data"
 * resultFile: { qualityResultFile } "Provides information about the data file containing the result coverage data"
 
Rules:
 - [ ] scope: maximum one
 - [ ] spatialRepresentationType: required, maximum one
 - [ ] spatialRepresentation: required, maximum one
 - [ ] resultContentDescription: required if resourceFormat is null and resultFile is null
 - [ ] resourceFormat:  required if resultContent is null, maximum one
 - [ ] resultFile: required if resultContent is null, maximum one
 
---
mdJson: **See [comment below](https://github.com/adiwg/mdJson-schemas/issues/255#issuecomment-1876176119) for updated schema**
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "coverageResult": [
                  {
                     "dateTime": "2019-06-11T09:00:00",
                     "scope": { },
                     "spatialRepresentationType": { },
                     "spatialRepresentation":  { },
                     "resultContentDescription": { },
                     "resourceFormat": { },
                     "resultFile": { }
                  }
               ]
            }
         ]
      }
   ]
}
````
