### ISSUE TITLE
Is dataDictionary an array?

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#27]
We have a difference between implementation and schema example.  

In the template dataDictionary is an object
In the reader handled as an object
In the example.json an array
In ISO 19115-1 and array (most likely).  MD_Metadata can have many md_ContentInformation which can be of subtype MD_FeatureCatalogue which can have many FC_FeatureCatalogue.  

So, do we want multiple data dictionaries?  If so we need patch a few items.

**Comment by jlblcc** [comment]
Are you referring to this example: https://github.com/adiwg/mdJson-schemas/blob/master/examples/dataDictionary.json?

If so, there is no problem. That file technically contains an *array of examples*.

**Comment by stansmith907** [comment]
True, forgot about that.  

But ISO 19115-1 support for multiple dictionaries still holds.  Should we allow multiple of not in our mdJson?

**Comment by jlblcc** [comment]
I thought we decided not to allow multiple dictionaries, but it's a trivial change as far as the schema.

**Comment by stansmith907** [comment]
I also thought we decided on only one dd, but I don't remember consulting the ISO standard in that decision process.  I'm still comfortable with only one dd per metadata file if others are.

**Comment by stansmith907** [comment]
In today's mdTools meeting we decided only one data dictionary per metadata record for mdJson.  We also decided to add an 'alias' element to entity and attribute.  see #29.

**Comment by jlblcc** [comment]
Per subsequent conversations, dataDictionary should be changed to an array.
