### ISSUE TITLE
AdditionalDocumentation

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdJson-schemas#30]
I found this section difficult to use. As a user you need to fully understand citation in order to utilize this section as one might intend. Citation forces an unnatural order of specifying a citation, who is responsible, and oh by the way I have a web site. What you really want as a user is to specify the document, what it is, describe it, supply the web link, then add a citation for the organization responsible (and their website). I’m not even quite clear how to hook this information in. I think we need to reorganize this section to a business orientation not an ISO orientation:
AdditionalDocumentation
	Name:
	Type:
	Description:
	Website:
	Document date:
	Provider
	     Name
	     Role

**Comment by jlblcc** [comment]
Maybe this is a result of the looking at additionalDocumentation in the schema viewer? Due to the "object-orientedness" of the schemas it appears much more complicated there than it really is. Here's what it looks like in the JSON:

```json
    {
      "resourceType": "publication",
      "citation": {
        "title": "A new high_precision borehole-temperature logging system used at GISP2, Greenland, and Taylor Dome, Antarctica",
        "date": [
          {
            "date": "1996",
            "dateType": "publication"
          }
        ],
        "responsibleParty": [
          {
            "contactId": "5",
            "role": "author"
          }
        ],
        "presentationForm": [
          "documentDigital"
        ],
        "onlineResource": [
          {
            "uri": "http://www.igsoc.org/journal.old/42/142/igs_journal_vol42_issue142_pg576-584.pdf",
            "protocol": "http",
            "name": "Journal of Glaciology",
            "description": "Publication document",
            "function": "download"
          }
        ]
      }
    }
```

**Comment by dwalt** [comment]
Yes, I think you identified the issue. The JSON is much more understandable
and logical. It is interesting the schema viewer can make the JSON seem
such a different animal at times. I think templates might help with this
level of understanding.
