### ISSUE TITLE
Definitions for dataDictionary

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdJson-schemas#31]
Need to write definitions(descriptions) for [dataDictionary](https://github.com/adiwg/mdJson-schemas/blob/master/schema/schema/dataDictionary.json).

**Comment by stansmith907** [comment]
Prototype definitions ...

- [ ] dataDictionary: "a description of the collection of physical objects or items in a data resource (schema)."

**Comment by jlblcc** [comment]
For now, we should add any dataDictionary definitions to the [spreadsheet](https://docs.google.com/a/arcticlcc.org/spreadsheets/d/1R8UeXPtCsWMcfUNDp9l79GXIczHuEdT1Qg3XKwyeys0/edit?usp=sharing)
