### ISSUE TITLE
Update dataDictionary - add dictionaryId

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdJson-schemas#327]
Add `dictionaryId` to the `dataDictionary` element. The `dictionaryId` is required to maintain the relation between a metadata record and an associated data dictionary. Dictionaries are often used as reusable components and should be treated the same as contacts. Without a `dictionaryId`, importing mdJSON results in the metadata record losing the link to a data dictionaries specified in the `mdDictionary` element.

Verify the following:
  - [x] Are changes required in the mdEditor
    - No. The mdEditor successfully imports mdJSON that contains a `dictionaryId` in a `dataDictionary` object.
  - [ ] Are changes required in the mdTranslator?
  - [ ] Is there a related ISO mapping (e.g., ISO 19110)?
    - [ ] Add `dictionaryId` to feature catalogue MD_Identifier array

---
Element Name: dictionaryId

Description: Unique identifier for the data dictionary.

Type: string (UUID)

Rules:
  - Required
  - only one
  
---
Translation:
```
"FGDC CSDGM":  []
"ISO 19115-2": []
"DCAT": [] 
```

---
mdJson:
```
{
  "dataDictionary" : [
    
    "dictionaryId" :  "character",
    (...remaining schema elements)
  ]
}
```

**Comment by hmaier-fws** [comment]
@dvonanderson 
Will adding this to the schema require any updates to the mdEditor? The editor already assigns a dictionaryId and it is part of the mdEditor-Json. It just doesn't get exported in the mdJson (See [end of line 45](https://github.com/adiwg/mdjson-examples/blob/639a3a3733ce0ca53660e4064cc088be32df4107/minimal-valid/min-valid-mdEditor-dict1-20240430.json#L45)). Possibly because it's not in the current schema.

@dwalt, @jwaspin 
Does ISO make use of a dictionary identifier anywhere (feature catalog?) It is not in the current schema and if it is used we need to create a mapping. I'm assuming that CSDGM does not make use the the identifier.

**Comment by dwalt** [comment]
@hmaier-fws Feature Catalogue does have MD_Identifier as an array.  CSDGM data dictionary does not support identifiers.
