### ISSUE TITLE
Definitions that need work

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#33]
Here are some suggested new definitions:

- [x] additionalDocumentation: "other documents related to, but not defining, the resource such as  factsheets, data catalog pages, award documents, proposals, and informational websites"

- [x] associatedResource: "other resources which are directly related to the central resource such as parent or child datasets or projects."

- [x] associationType: "identifies how the associated resource is related to the central resource such as 'is a component of', 'larger work citation', 'sub-project', etc." 

- [x] initiativeType: "Identifies type of initiative under which the resource was produced - the activity that resulted in the resource."

- [x] graphicOverview: "provides a link to images, maps, flow charts, data models, etc. that visually help to understand the resource."

- [x] graphicOverview.fileName: "name of the file that contains a graphicOverview for the resource."  Note: the current definition references **browseGraphic** which is the ISO name rather than the mdJson name **graphicOverview**. 

- [x] graphicOverview.fileDescription: Note: change **browseGraphic** to **graphicOverview**

- [x] graphicOverview.fileType: "the format in which the illustration is encoded such as GIF, JPEG, PBM, PS, TIFF."

- [x] graphicOverview.fileURI: Note: change **browseGraphic** to **graphicOverview**

- [x] dataQuality: "describes the data quality, lineage, and/or processing steps that were applied to the whole or part of the data resource"

- [x] dataQuality.lineage: "procedural (non-quantitative) data quality information about the portion of the data resource identified in the dataScope"

- [x] dataQuality.lineage.statement: "a general statement of the actions taken to verify, transform, repair, and integrate the data described in the dataScope"

- [x] dataQuality.lineage.processStep: "a brief statement describing an individual, non-trivial process or methodology step taken in development of the resource data described in the dataScope"

- [x] dataQuality.lineage.source: "provides information about the source data used in creating the data specified in the dataScope"

- [x] dataQuality.lineage.source.description: "a brief description about the source dataset used in creating the data specificed in the scope"

- [x] dataQuality.lineage.source.citation: " a citation providing information about the source dataset including a link or other access instructions"

- [x] dataQuality.lineage.source.processStep: "a description of a non-trivial event or transformation taken to prepare the source data for use as the data specified in the scope"

- [x] resourceSpecificUsage.specificUsage: "a brief description about how the resource is being used"

- [x] resourceSpecificUsage.userDerterminedLimitations: "a brief description of applications determined by the user for which the resource is not suitable"

- [x] resourceSpecificUsage.userContactInfo: "identification of persons and/or organizations and their roles that are using this resource"

- [x] distributorInfo.distributionTransferOptions: "technical means and media by which a resource is obtained from the distributor" 

- [x] extent.geographicElement: "an array of objects each describing a geographic boundary or location comprising all or portion of the resource"

- [x] extent.temporalElement: "an array of objects each describing a temporal boundary or location comprising all or portion of the resource"

- [x] extent.verticalElement: "an array of objects each describing a vertical boundary or location comprising all or portion of the resource"

- [ ] extent.geographicElement.featureScope: "a brief statement describing the portion of the extent covered by this geographic element"

- [x] taxonomy.voucher.specimen: "a word or phrase describing the type of specimen collected.  e.g. 'herbarium specimens', 'blood samples', 'photographs', 'individuals'".

- [ ] extent.temporalElement: "Temporal context for the extent".

- [x] temporalElement.timeInstant.id: "a user provided unique identifier for the timeInstant".

- [x] temporalElement.timeInstant: "a dateTime associated with an ID and description".

- [x] temporalElement.timeInstant.description: "a brief description providing relevant information about the date and time". 

- [x] temporalElement.timePeriod: "object identifies a period of time relevant to the extent". 

- [x] temporalElement.timePeriod.id: "a user provided unique identifier for the timePeriod".

- [x] temporalElement.timePeriod.description: "a brief description providing relevant information about the datetime period".

**Comment by stansmith907** [comment]
I made it through the documentation of the internal object and have made all the changes to the definitions I plan to make.  Time to review these and move them to the schema.

**Comment by jlblcc** [comment]
I don't think this def is correct:
> extent.geographicElement.featureScope: "a brief statement describing the portion of the extent covered by this geographic element"

This one was a duplicate(I used the first one):
>extent.temporalElement: "Temporal context for the extent"

**Comment by stansmith907** [comment]
extent.geographicElement.featureScope was one of the two properties added to a feature by Allison.  She was using it to identify 'borehole's.  These are entered as individual objects in a feature array.  It's sort of a 'feature' type as opposed to the geometry type.  Maybe ...

"a brief statement describing the object covered by this geographic element"

Not sure that's much better.

**Comment by jlblcc** [comment]
Since this is attached to the feature, how about: "a word or phrase identifying the type of object described by the *feature*."

**Comment by nunatech** [comment]
Chiming in kind of late... a more generic term for something like boreholes in our use case would be "data collection site" as opposed to "logistics base" for the feature.

**Comment by stansmith907** [comment]
works for me

On Fri, May 1, 2015 at 12:27 PM, Allison Gaylord <notifications@github.com>
wrote:

> Chiming in kind of late... a more generic term for something like
> boreholes in our use case would be "data collection site" as opposed to
> "logistics base" for the feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adiwg/mdJson-schemas/issues/33#issuecomment-98227565>.
>



-- 
Stan Smith
Alaska Science Center
Data Manager
907-786-7072 Office
907-223-8752 Mobile
stansmith@usgs.gov
