### ISSUE TITLE
Add characterSet to resourceInfo

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdJson-schemas#35]
Is there a reason we left this out, or was it just an oversight?

**Comment by stansmith907** [comment]
I guess we can call it an oversight.  I checked our ISO class model and found we had not included it from the beginning.  It would not be hard to include and doing so would not break anything we already have.

**Comment by jlblcc** [comment]
How's this look: https://github.com/adiwg/mdJson-schemas/commit/6bc6a38ffbc0746500ed9e3054c9267f1181b6dd
