### ISSUE TITLE
Missing ISO translations for Associated Resource codelists

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdJson-schemas#38]
Missing ISO translations and/or examples for Resource Type, Iniative Type and Association Type

**Comment by jlblcc** [comment]
Everything under [schema{ } > metadata{ } > associatedResource[ ]](http://www.adiwg.org/mdTools/#viewer-page?v=2-3) is missing an example. Looks like the translations are all accounted for. *resourceType* is mdJSON only - no translation.

**Comment by dwalt** [comment]
The translation info is missing in the schema viewer, so may just need to
be added in schema documentation. Stan indicated that resourceType maps to
MD_ScopeCode, but perhaps that is a -1 implementation.

**Comment by jlblcc** [comment]
AFAIK there is no mapping for *resourceType* under *associatedResource* or *additionalDocumentation*. I believe we added those as mdJSON-only properties. We don't currently have a way to document codelists *for mdJSON* in the schemas.

**Comment by stansmith907** [comment]
In 19115-2 MD_ScopeCode is set as hierarchyLevel[0..*] with default of
'dataset' (in our metadataInfo section).  We just have it defaulting to
'dataset' and forgot to go back at pick it up once we added resourceType to
resourceInfo.  We should go back and fix this.  But should we make
resourceType an array?

In 19115-1 MD_MetadataScope is a new class with referenceScope of type
MD_ScopeCode defaulting to 'dataset'.  MD_MetadataScope is linked to
MD_Metadata somehow, need to see 18115-3 to tell how.

On Fri, Jun 12, 2015 at 4:29 PM, Josh Bradley <notifications@github.com>
wrote:

> AFAIK there is no mapping for *resourceType* under *associatedResource*
> or *additionalDocumentation*. I believe we added those as mdJSON-only
> properties. We don't currently have a way to document codelists *for
> mdJSON* in the schemas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adiwg/mdJson-schemas/issues/38#issuecomment-111646409>
> .
>



-- 
Stan Smith
Alaska Science Center
Data Manager
907-786-7072 Office
907-223-8752 Mobile
stansmith@usgs.gov

**Comment by jlblcc** [comment]
What do you mean by we "forgot to go back at pick it up"? Are you talking about in the writer?

The only reason I can see to make it array is to support some kind of "clloection-level" metadata record where you have mixed data types. Not sure how much that happens, but it generally seems like a bad idea. However, we're not the metadata police...

As far as the mapping, I can map *resourceType* under *associatedResource* or *additionalDocumentation* to *[MD_ScopeCode]* directly. Does that work?

**Comment by stansmith907** [comment]
"Are you talking about the writer?" - Yep.  The writer just puts 'dataset'
for everything.  We did this early on before we added resourceType to the
mdJson.

I also don't find a need to make resourceType an array and think it may be
more confusing than keeping it a scalar.

I was thinking that resourceType was under both associatedResource and
additionalDocuemtation.  And both should map to MD_ScopeCode.  I went to
look at mdTools and found that modes are not responding to mouse clicks.
Reloaded it twice to test.  Did you push something out recently?

On Mon, Jun 15, 2015 at 9:02 AM, Josh Bradley <notifications@github.com>
wrote:

> What do you mean by we "forgot to go back at pick it up"? Are you talking
> about in the writer?
>
> The only reason I can see to make it array is to support some kind of
> "clloection-level" metadata record where you have mixed data types. Not
> sure how much that happens, but it generally seems like a bad idea.
> However, we're not the metadata police...
>
> As far as the mapping, I can map *resourceType* under *associatedResource*
> or *additionalDocumentation* to *[MD_ScopeCode]* directly. Does that work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adiwg/mdJson-schemas/issues/38#issuecomment-112139642>
> .
>



-- 
Stan Smith
Alaska Science Center
Data Manager
907-786-7072 Office
907-223-8752 Mobile
stansmith@usgs.gov

**Comment by dwalt** [comment]
Correct, resource type appears in both Associated Resource and Additional
Documentation, according to the Schema Viewer.

**Comment by stansmith907** [comment]
Hey Josh -

Just tested mdTools again and it was working (slowly) in IE but no response
from nodes in Chrome.

On Mon, Jun 15, 2015 at 9:38 AM, dwalt <notifications@github.com> wrote:

> Correct, resource type appears in both Associated Resource and Additional
> Documentation, according to the Schema Viewer.
>
> On Mon, Jun 15, 2015 at 9:31 AM, stansmith907 <notifications@github.com>
> wrote:
>
> > "Are you talking about the writer?" - Yep. The writer just puts 'dataset'
> > for everything. We did this early on before we added resourceType to the
> > mdJson.
> >
> > I also don't find a need to make resourceType an array and think it may
> be
> > more confusing than keeping it a scalar.
> >
> > I was thinking that resourceType was under both associatedResource and
> > additionalDocuemtation. And both should map to MD_ScopeCode. I went to
> > look at mdTools and found that modes are not responding to mouse clicks.
> > Reloaded it twice to test. Did you push something out recently?
> >
> > On Mon, Jun 15, 2015 at 9:02 AM, Josh Bradley <notifications@github.com>
> > wrote:
> >
> > > What do you mean by we "forgot to go back at pick it up"? Are you
> talking
> > > about in the writer?
> > >
> > > The only reason I can see to make it array is to support some kind of
> > > "clloection-level" metadata record where you have mixed data types. Not
> > > sure how much that happens, but it generally seems like a bad idea.
> > > However, we're not the metadata police...
> > >
> > > As far as the mapping, I can map *resourceType* under
> > *associatedResource*
> > > or *additionalDocumentation* to *[MD_ScopeCode]* directly. Does that
> > work?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/adiwg/mdJson-schemas/issues/38#issuecomment-112139642
> >
> > > .
> > >
> >
> >
> >
> > --
> > Stan Smith
> > Alaska Science Center
> > Data Manager
> > 907-786-7072 Office
> > 907-223-8752 Mobile
> > stansmith@usgs.gov
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/adiwg/mdJson-schemas/issues/38#issuecomment-112147740>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adiwg/mdJson-schemas/issues/38#issuecomment-112149373>
> .
>



-- 
Stan Smith
Alaska Science Center
Data Manager
907-786-7072 Office
907-223-8752 Mobile
stansmith@usgs.gov
