### ISSUE TITLE
Add PT_Locale to meet requirements of Traditional Knowledge (TK)

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#39]
I just received an advance copy of a study conducted at U. Idaho regarding handling of TK research projects.  Among other things the study lays out the requirements for metadata using the ISO standard.  An important issue for them is locale (PT_Locale).  This goes in the MD_Metadata or MI_Metadata section.  Unfortunately we missed it, probably because it is also missing from the ISO documentation, but it is present in the XSD.  

````xml 
   <gmd:locale>
	   <gmd:PT_Locale>
			<gmd:languageCode>
				<gmd:LanguageCode codeList="" codeListValue=""></gmd:LanguageCode>
			</gmd:languageCode>
			<gmd:country>
				<gmd:Country codeList="" codeListValue=""></gmd:Country>
			</gmd:country>
			<gmd:characterEncoding>
				<gmd:MD_CharacterSetCode codeList="" codeListValue=""></gmd:MD_CharacterSetCode>
			</gmd:characterEncoding>
		</gmd:PT_Locale>
   </gmd:locale>
   <gmd:locale></gmd:locale>
````

Locale is an array.  Unfortunately it overlaps language and characterSet.  In -1 language and characterSet were completely replaced by defaultLocale (PT_Locale [0..1]) and otherLocale (PT_Locale [0..*]) - same in MD_DataIdentification for -1.  Making this change will break the backwards compatibility of mdJson v1.  

Should we break it now rather than waiting to support -1?  One other difference, gmd:language is a gco:CharacterString, gmd:languageCode is a codeList.  Both the LanguageCode and CountryCode may be a pain to add to mdCodes.  I'll look into it.

**Comment by stansmith907** [comment]
In a discussing with Josh, we decided to add 'locale' to mdJson and keep (but deprecate) metadataCharacterSet, resourceLanguages, and resourceCharacterSets.  The deprecated attributes will be removed from mdJson at version 2.0, likely to happen when we make changes to support 19115-1.

````ruby
    def newLocale
        intObj = {
            languageCode: nil,
            countryCode: nil,
            characterEncoding: nil
        }
    end
````
Locate will fit into the mdJson as follows ...
````json
  "metadata": {
    "metadataInfo": {
      "metadataIdentifier": {},
      "parentMetadata": {},
      "metadataContact": [],
      "metadataCreationDate": "0000-00-00",
      "metadataLastUpdate": "0000-00-00",
      "metadataCharacterSet": "utf8",
      "metadataLocale": [
        {
          "language": "",
          "country": "",
          "characterSet": ""
        }
      ],
````
and
````json
  "metadata": {
    "metadataInfo": {},
    "resourceInfo": {
      "resourceType": "",
      "citation": {},
      "resourceTimePeriod": {},
      "pointOfContact": [],
      "abstract": "",
      "shortAbstract": "",
      "status": "",
      "hasMapLocation": true,
      "hasDataAvailable": true,
      "language": [""],
      "characterSet": ["utf8"],
      "locale": [
        {
          "language": "",
          "country": "",
          "characterSet": ""
        }
      ],
````

**Comment by jlblcc** [comment]
Added locale to template: https://github.com/adiwg/mdJson-schemas/commit/2ac288298e7b1aed9dd0da11fcadd19c021788aa#diff-ec3083330efb787fe8d0aae5be743335R86
