### ISSUE TITLE
graphicOverview 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#45]
"graphicOverview" has added one new element in ISO -1.  

Changes: 
1. “fileConstraint” object was added to graphicOverview to identify, legal, security, and other constraint requirements associated with use and distribution of the graphic.  
2. “fileURI” for graphicOverview is now a full onlineResource (issue #50) rather than a simple URI string. 

``` json
{
   "fileName": "",
   "fileDescription": "",
   "fileType": "",
   "fileConstraint": [
      {
         "see": "constraint 2.0"
      }
   ],
   "fileUri": [
      {
         "see": "onlineResource 2.0"
      }
   ]
}
```

XML example: browseGraphic -3.xml

**Comment by jlblcc** [comment]
So what are the thoughts on including a "datauri" property to allow direct embedding of browseGraphic images?

Here's an [example](http://jsfiddle.net/eider11/686ms3wx/)

**Comment by mmheller** [comment]
Great idea, the communication staff types would appreciate the ability to display embedded images.

**Comment by jlblcc** [comment]
Is `fileConstraint` supposed to be an array or an object? [This example](https://github.com/stansmith907/mdTranslator/blob/dev/test/readers/mdJson/testData/graphic.json#L7) shows it as an array, which contradicts the one above. I'm not sure I see the benefit of having an array here, since the properties themselves are arrays.

**Comment by jlblcc** [comment]
Instead of a dataURI property, I added "dataUri" to the [onlineFunction codelist](https://github.com/adiwg/mdCodes/commit/098bb1e6b19bcb504afc3576322ee309fe585b53).

**Comment by stansmith907** [comment]
So what is your method for camel case naming? Universal resource identifier is URI. Uri is not a word. Should we treat all abbreviations as words?

**Comment by stansmith907** [comment]
I'll need to check the file constraint schema. I think this one was laid in early and not updated as constraint was worked. The example you point to looks better. At least it includes security constraints.

**Comment by stansmith907** [comment]
Good catch, I did forget to revisit this issue after completing constraint.  One of the ISO loops, constraint is in graphic and graphic is in constraint.  The JSON example has been updated.

**Comment by jlblcc** [comment]
I was just following the *mdJson* approach to camelCasing. Personally, I prefer to capitalize the acronyms, e.g. _mdJSON_ or _dataURI_. At least if they form the last "word".

**Comment by stansmith907** [comment]
Yeah, I like your rule, at least it's good to have one for consistency.  I'll leave it as *URI* and look for other places I may have used *uri* and change them.
