### ISSUE TITLE
constraint 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#47]
“constraint” is now an array and has undergone major changes from mdJson 1.0.  The new elements added repeat for legal (issue #56) and security (issue #57) constraints and are not redefined in those issues.  

Changes: 
1. "type" is an ADIwg enumeration of type string.  Valid values are [ use | legal | security ].  If type = "legal" the "legalConstraint" object must be present and filled in.  If type = "security" the "securityConstraint" object must be present and filled in.
2. "scope" is a new object ("constraintApplicationScope" in ISO) of type MD_Scope.  Definition: "spatial and/or temporal extent and or level of the application of the constraint restrictions."  I have limited the extent to either description or temporal extents; and only time period within temporal extents.  See issue #100.
3. “graphic” is a new array of type MD_BrowseGraphic.  Definition “graphic/symbol indicating the constraint”.  This will use the mdJson browseGraphic 2.0 (issue #45).
4. “reference” is a new array of type CI_Citation.  Definition: “citation for the limitation or constraint. Example Copyright statement.”  I used the abbreviated form of citation we created for authority (issue #54).
5. “releasability” is a new object of type MD_Releasability (issue #51).  Definition: “information concerning the parties to who the resource can or cannot be released."  The following elements are supported...
   - "addressee" is a new array of  CI_Responsibility (issue #52).  Definition: "party to which the release statement applies". 
   - "statement" is a new scalar of type character.  Definition: "release statement".
   - "disseminationConstraint" is a new array of type MD_RestrictionCode.  Definition: "component in determining releasability."
6. “responsibleParty” is a new array of type CI_Responsibility (issue #52).  Definitions: “party(s) responsible for the resource constraint”.  
7. "legal" is an object of type "legalConstraint".  Required if "type" = "legal".
8. "security" is an object of type "securityConstraint".  Required if "type" = "security".

``` json
{
   "constraint": [
      {
         "type": "use",
         "useLimitation": [""],
         "scope":{
            "see": "scope 2.0"
         },
         "graphic": [
            {
               "see": "graphicOverview 2.0"
            }
         ],
         "reference": [
            {
               "see": "citation 2.0"
            }
         ],
         "releasability": {
            "addressee": [
               {
                  "see": "responsibility 2.0"
               }
            ],
            "statement": "",
            "disseminationConstraint": ["MD_RestrictionCode"]
         },
         "responsibleParty": [
            {
               "see": "responsibility 2.0"
            }
         ],
         "legal": {
            "see": "legalConstraint 2.0"
         },
         "security": {
            "see": "securityConstraint 2.0"
         }
      }
   ]
}
```

see XML example useConstraint -3.xml

**Comment by jlblcc** [comment]
Aren't _constraint->reference->responsibleParty_ and _constraint->responsibleParty_ redundant? Do we need both?

**Comment by stansmith907** [comment]
Are they the same? No.  Do we need both?  Don't know.  *constraint > reference >responsibleParty* is the responsible party within citation.  *constraint > responsibleParty* is the responsible party for the constraint.  Personally I would not fill in the responsible party for the citation.

**Comment by jlblcc** [comment]
What's the difference between "useLimitation" and  "legalConstraint > useConstraint". Are these equivalent?

Given the updated structure, I don't see why we can't put the properties from `legalConstraint` and `securityConstraint` into the root `constraint` object. The property names are all distinct, and since `type` is required I don't see a need to maintain these separate objects.

**Comment by stansmith907** [comment]
All the elements of 'constraint' and also valid in 'legalConstraint' and 'securityConstraint'.  I repeated the elements in mdJson so that populating 'constraint' elements would not be a prerequisite to declaring a legal or security constraint.  This also works nicely with using 'type=' to set the constraint type.  This way all the constraints types can be elements of the same 'constraint' array and mixed in whatever order.  All constraints look the same, just that legal and security constraints have a few additional elements.  These types are normalized in the internal object.  

'useLimitation' is a limitation for using the data that is neither legally binding or a security restriction.

**Comment by jlblcc** [comment]
I still don't see why we need the extra objects if we're declaring a type. Seems like we can just have one constraint object with all the properties. Choosing a type would determine which ones are required.

**Comment by stansmith907** [comment]
Declaring the type does not set requirements since none of the legalConstraints are required and only one secruityConstraint is required.  Type only sets which elements are available.  Typically I don't like to combine rule sets.  If the constraint type='use' legal and security elements are not allowed, if type='legal' one legal element is required but no security elements, etc.  Putting all the elements in one objects puts more work on the application.  But do what you want, I'll adjust.

**Comment by stansmith907** [comment]
If you change to a single object do set some rules for me.  Are we still declaring type?  If the user set attributes outside of the declared type do we discard them?  If the use specifies both legal and security elements do we generate multiple constraints?  etc.

**Comment by jlblcc** [comment]
Yeah, that only works if we're declaring "type". If the user sets attributes outside of the declared type I wouldn't just ignore them. In the case of the mdTranslator I'd read them in and handle any discards in the writer. I can set required properties in the schema based on the type.

**Comment by stansmith907** [comment]
It will make no sense if the user set attributes outside the declared type so they should be discarded.  Actually, the common elements define the constraint and the extra legal or security set aspects of specific types of constraints.  Legal and security constraints are two different constraints and would correspondingly  have different use type elements.  

Remember too constraints are complex.  Last time I modified constraints it impacted 30 modules.

**Comment by jlblcc** [comment]
Here's an example of dropping the explicit "type" declaration. Instead of reading the type from the "type"  property([like this](https://github.com/stansmith907/mdTranslator/blob/dev/lib/adiwg/mdtranslator/readers/mdJson/modules/module_constraint.rb#L37)), we can just grab it from the constraint property name:

```ruby
type = %w{ legal security useLimitation}.find { |word| hConstraint.has_key?(word)}
```

If no "legal" or "security" property exists, then type will be `useLimitation` (the schema requires at least one of those properties). Note, that the type can still be set on the internal object, so no change to the writer. This example is probably the most complicated since it's mixing in other properties and we're not dealing with separate objects. Thoughts?

**Comment by stansmith907** [comment]
Not sure how this would work in all Ruby compilers.  Legal and security constraints also have useLimitations.  The find block would search for all the types in the list until one is found, but order is not required in JSON, so the mdJson file could place these blocks in any order.

**Comment by stansmith907** [comment]
"useLimitation" is not required, so may not be present in which nil would be returned (no problem) if "security" or "legal" we also not present.  However, "legal", "security", and "useLimitation" could all be present in any mdJson "constraint" object in which case the presence of an element does not guarantee the type of constraint.

**Comment by jlblcc** [comment]
Yeah, I think that's a problem. We probably shouldn't allow both "security" and "legal" in the same object instance if we're relying on "type". I think it's not very clear that if you set type="legal", the "security" object is not going to be translated.

**Comment by stansmith907** [comment]
We can't get completely away from it.  "useLimitation" is present in all types.  It's impossible to control what elements are present in JSON not knowing the creation source.  All we could do is reject the file.  I don't think we need to go to that extreme.  This is a tricky one and the only one quite like it.  I have reorganized it 3 times now.  The last time took 1.5 days and effected 37 modules.
