### ISSUE TITLE
contact 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#48]
Changes: 
1. "contactId" is a required element of type string. It was added by ADIwg to support referencing contacts from elsewhere in the metadata record.
2. “isOrganization” is a required element of type Boolean.  It was added by ADIwg to specify whether the contact is for an individual or organization.  The default value is false.
3. “name” is a required element of type string.  It replaces both “organizationName” and “individualName” in mdJson 1.0 since only one name is allowed for a contact now.
4. “positionName” will only be valid for individual contacts.
5. “memberOfOrganization” array was added to hold organization “contactId”s that this individual has some relationship to.  Will only be valid for individual contacts.
6. “logoGraphic” array was added for organizations to provide their access to their logos.  logoGraphic uses the BrowseGraphic object which has changed from previous ISO format.  ~~Will only be valid for organization contacts.~~  Issue #45.
7. “address” is now an array of addresses.  Address format has not changed.  Issue #115.
8. “onlineResource” does not include ISO attributes “applicationProfile” and “protocolRequest” for contact. Issue #50.
9. “phone” is the new name for “phonebook”.   Issue #114.
10. “hoursOfService” was added as an array of character strings.  note: This field is also supported in FGDC. 
11. “contactType” was added as a user defined contact type. 
12. "electronicMailAddress" is an array of strings.  It was moved to the base of 'contact' from 'address'. 

``` json
{
   "contact": [
      {
         "contactId": "",
         "isOrganization": false,
         "name": "",
         "positionName": "",
         "memberOfOrganization": [
            "organization contact ID"
         ],
         "logoGraphic": [
            {
               "see": "graphic 2.0"
            }
         ],
         "phone": [
            {
               "see": "phone 2.0"
            }
         ],
         "address": [
            {
               "see": "address 2.0"
            }
         ],
         "electronicMailAddress": [""],
         "onlineResource": [
            {
               "see": "onlineResource 2.0"
            }
         ],
         "hoursOfService": [""],
         "contactInstructions": "",
         "contactType": ""
      }
   ]
}
```

No ISO XML example

**Comment by jlblcc** [comment]
Is there a way to add additional identifiers or aliases to the contact object? Possibly:

- [ ] add  array of md_identifier
- [ ] use the onlineResource array

**Comment by jlblcc** [comment]
Remove _primaryRole_.

**Comment by stansmith907** [comment]
*primaryRole* has been removed.

**Comment by jlblcc** [comment]
I think we need to be more nuanced in handling `name` and `position`. Often it is desirable to only list a position and not an individual's name in the metadata.  The current schema will not allow this - `name` is required for both types of contact. I suggest adding the following rules:

- isOrganization=true and name is required
- isOrganization=false and (name or positionName) is required
