### ISSUE TITLE
identifier 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#49]
The new MD_Identifier combines the MD_Identifier and RS_Identifier (i.e. used in imageQuality and other places in -2).  I have combined the two so only a single form is supported in mdJson 2.0.  

Changes:  
1. “identifier” (or “code” in ISO) is a scalar of type character string.  Definition: “alphanumeric value identifying an instance in the namespace.”
2. “namespace” (or “codeSpace” in ISO) is a scalar of type character string.  Definition: “identifier or namespace in which the code is valid.”
3. “version” is a scalar of type character string.  Definition: “version identifier for the namespace”.
4. “description” is a scalar of type character string.  Definition: “natural language description of the meaning of the code value.”  We can use this attribute to replace the “type” attribute in mdJson 1.0.
5. “authority” is an abbreviated citation object.  Definition: “the person or party responsible for maintenance of that namespace.” I limited the number of citation attributes in mdJson 2.0 (as we did in 1.0).  Issue #54.
6. "type" element was dropped in mdJson 1.0.  It was internal only to mdJson and had no output in -2 or -1.  "description" is adequate to handle "type" if necessary. 

``` json
{
   "identifier": "",
   "namespace": "",
   "version": "",
   "description": "",
   "authority": {
      "see": "citation 2.0"
   }
}
```

see XML example citation -3.xml

**Comment by jlblcc** [comment]
We need type. It was being used to specifically identify, well, the _type_. I believe we're also using it to id ISBN and ISSN in -2, since those are actual elements. Beyond that, we need it to id DOI's and such. It should probably be backed by a codelist of suggested types.

**Comment by stansmith907** [comment]
I was thinking *type* would fit in *namespace*, I think they are the same thing.  Namespace is a simple character string, not a URI, which would be placed within authority.  Perhaps calling it *codeSpace* as it is in ISO would help.  But there were objections to using that name when designing mdJson 1.0.

**Comment by jlblcc** [comment]
OK, I stand corrected. We'll need to make sure that we indicate that the "official" namespace should be used when one exists, like:

- urn:ISBN
- urn:ISSN
- info:doi/ 
- info:ark/
