### ISSUE TITLE
onlineResource 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#50]
Changes: 
1.  “protocolRequest” was added to onlineResource but not used in mdJson 2.0.  Definition: “request used to access the resource depending on the protocol (to be used mainly for POST requests).”  No changes from mdJson 1.0.

``` json
            "onlineResource": [
                {
                    "uri": "http://thisisanexample.com",
                    "protocol": "",
                    "name": "",
                    "description": "",
                    "function": ""
                }
            ],
```

see XML example responsibleParty -3.xml

**Comment by stansmith907** [comment]
In our effort to conform to naming standards for mdJSON elements we adopted a convention to capitalize acronyms.  What if the element name is an acronym, as *uri* above?

- [ ] uri
- [ ] URI
- [ ] uRI
- [x] resourceURI

**Comment by jlblcc** [comment]
Why did we change this to `resourceURI`?  I prefer just plain `uri`. If the property name is a single acronym, I'd just lowercase the whole thing. I don't really care as long as it's consistent. In fact, why don't we just treat acronyms as lowercase words. That follows KISS logic.

So:
- uri
- resourceUri
- resourceJsonUri
- resourceJsonUriUsa

**Comment by stansmith907** [comment]
Great, I just went through and changed them all to upper case per our earlier discussion.

**Comment by jlblcc** [comment]
My bad. Do you want to leave them upper-cased?

**Comment by stansmith907** [comment]
All choices are bad. Can't start name with upper case, don't want mixed case, if acronym not first word pushed to camel case. So no right answer. 

If uppercase, acronym cannot be first word. 
If lowercase, acronym must be first word. 

Your choice.

**Comment by jlblcc** [comment]
That's why I was suggesting that we just treat them as "normal" words. Just camel-case like any other word.
