### ISSUE TITLE
responsibility 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#52]
CI_Responsibility was formerly CI_ResponsibleParty.  The schema described here is the mdJson 2.0 schema and not part of ISO.  It makes use of data maintained as individual and organization contacts saved in the mdJson contacts array.  

The new ISO -3 schema centers on “role” rather than the contact.  

Changes to the mdJson: 
1. "roleExtent" is a new array of EX_Extent objects added to define the extent for the role.  ISO allows for full geographic, vertical, and temporal extents but I have limited mdJson to the elements of "description" and "temporalExtent [ ]", ("timeInstant", "timePeriod").  However, "geographicExtent [ ] and verticalExtent [ ] could be included with no changes to the software, it's ready to receive these.
2. “party” is a new array added to identify all the individual and/or organization contacts associated with the role. 
   - “partyType” is a new enumerated type added (individual or organization) to identify the type of party being described.
   - “organizationMembers” is a new array of individual contactId(s) identifying individuals that have an association with an organization contact.  Valid only for party with partyType = “organization”.  

``` json
{
   "role": "CI_RoleCode",
   "roleExtent": [
      {
         "see": "extent 2.0"
      }
   ],
   "party": [
      {
         "contactId": "",
         "organizationMembers": [
            "individual contact ID"
         ]
      }
   ]
}
```

no ISO example

**Comment by jlblcc** [comment]
Remove _partyType_.

**Comment by jlblcc** [comment]
_roleExtent_ should be an array.

**Comment by stansmith907** [comment]
Replace start and end date with temporalExtent.

**Comment by stansmith907** [comment]
*partyType* has been removed.

**Comment by stansmith907** [comment]
I had limited the role extent to one object since I did not allow the expression of a full EX_Extent.  The full EX_Extent would permit descriptive, graphic, vertical, as well as temporal extents to be defined.  But technically this is an array in ISO.  I have made the change per your request but have not opened the mdJson for other than temporal extents.

**Comment by jlblcc** [comment]
Why don't we just use _timePeriod_ instead of _roleExtent_? The use of _extent_ is confusing. In fact, I would suggest dropping the use of _extent_ anywhere we're restricting the type of extent - we don't need to wrap them in an additional layer. Just add the geographic, vertical, or temporal extent properties directly to the object in question.

**Comment by jlblcc** [comment]
>  Just add the geographic, vertical, or temporal extent properties directly to the object in question.
Unless we're allowing all three.

**Comment by stansmith907** [comment]
Fair enough.  If we are going to call it *timePeriod* it may as well be the full *timePeriod*.  I changed *roleExtent* to *timePeriod*.

**Comment by jlblcc** [comment]
"timePeriod" should be an array, right? Example shows it an an object. Also see [here](https://github.com/stansmith907/mdTranslator/blob/dev/lib/adiwg/mdtranslator/internal/internal_metadata_obj.rb#L217).

**Comment by stansmith907** [comment]
Yep, right you are.  I missed it since "responsibility" with "extent" is a new construct in -1.  So, I had not tested yet.  I'll patch it now.

**Comment by stansmith907** [comment]
I changed "timePeriod" out for the full "extent".  Not only does this match the ISO 19115-1 standard, it was getting confusing limiting extent type to "timePeriod" when there were different use cases for responsibility.
