### ISSUE TITLE
series 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#53]
CI_Series was part of ISO 19115-2 but not included in mdJson 1.0.  I have added it to mdJson 2.0

Changes: 
1. “seriesName” is a scalar of type character string.  Definition: “name of the series, or aggregate resource, of which the resource is a part.”
2. “seriesIssue” is a scalar of type character string.  Definition: “information identifying the issue of the series.”
3. “page” is a scalar of type character string.  Definition: “details on which pages of the publication the article was published.”

``` json
            "series": {
               "seriesName": "",
               "seriesIssue": "",
               "issuePage": ""
            },
```

see XML example citation -3.xml

**Comment by jlblcc** [comment]
Is this in citation?

**Comment by stansmith907** [comment]
Yep.

**Comment by stansmith907** [comment]
Just finished pushing out objects I have reviewed. These are now in 9 issues. There are a lot of moving parts so observe with caution, I'm sure there are errors or explanations which are confusing our lacking. I also pushed out 3 XML examples into mdTranslator doc folder.

**Comment by stansmith907** [comment]
Like I think I just got constraints all wrong.
