### ISSUE TITLE
authority 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#54]
"authority" is a short version of CI_Citation.  I use it many places a full citation is not needed.  There are no changes from mdJson 1.0 other than those made to responsibleParty.  

Discussion: 

1. Should we keep "authority" or just open every opportunity to the full CI_Citation?

Changes: 

1. "responsibleParty" has changed to support the division of individual and organization contacts.  See "responsibility 2.0" (issue #52). 

````json
{
   "title": "",
   "date": [
      {
         "date": "0000-00-00",
         "dateType": ""
      }
   ],
   "responsibleParty": [
      {
         "see": "responsibility 2.0"
      }
   ],
   "onlineResource": [
      {
         "see": "onlineResource"
      }
   ]
}
````
see ISO XML example authority -3.xml

**Comment by jlblcc** [comment]
The only benefit I see to keeping the short version is to simplify the schema visualization. Other than that I don't think it matters.

**Comment by stansmith907** [comment]
I've been dropping out as I work through the reader. Replacing with full citation.

**Comment by stansmith907** [comment]
I have replaced all instances of *authority 2.0* with *citation 2.0*.  

Closing this issue.
