### ISSUE TITLE
spatialRepresentation 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#60]
"spatialRepresentation" has not changed from -2 to -1.  Definition: "method used to spatially represent geographic information."

Changes: 

1. "vectorRepresentation",  "georectifiedRepresentation", and "georeferencableRepresentation" were not implemented in mdJson 1.0.

``` json
{
   "spatialRepresentation": [
      {
         "gridRepresentation": {
            "see": "gridRepresentation 2.0"
         }
      },
      {
         "vectorRepresentation": {
            "see": "vectorRepresentation 2.0"
         }
      },
      {
         "georectifiedRepresentation": {
            "see": "georectifiedRepresentation 2.0"
         }
      },
      {
         "georeferenceableRepresentation": {
            "see": "georeferencedRepresentation 2.0"
         }
      }
   ]
}
```

see ISO XML example spatialReference -3.xml

**Comment by jlblcc** [comment]
Can't we drop type and just use the property name?

**Comment by stansmith907** [comment]
Maybe.  I used the 'type' convention on your suggestion a while back. Taking type out of all these classes may make the schema simpler (and more confusing in my opinion) but will complicate the readers, writers, and editor since each of the types connects to a different class.  I need to know what class to pass things to.  It will also be considerable work to remove type and rewrite the logic in all the modules, tests, and test data.  So, unless it is causing us harm to have 'type'...

**Comment by jlblcc** [comment]
I'm just talking about this one object. In this instance, type is totally redundant because you can only have one "type" _and_ they're all different. This is kind of a weird example, since we're lumping completely different classes.

If it's going to be a pain to rewrite, I can restore the "type".

**Comment by jlblcc** [comment]
You can get the class from the property name. Shouldn't be any more work than using the type?

**Comment by jlblcc** [comment]
Another option is to move "type" into the objects themselves.

**Comment by jlblcc** [comment]
So the current example looks like this: https://github.com/adiwg/mdJson-schemas/blob/15c47d69abcf9530b98a9b027c0ddaab770f025c/examples/spatialRepresentation.json

**Comment by stansmith907** [comment]
I think your above example is the same as what I intended to convey in the model above.  Although not clear, I intended only one of the spatial representation object to be present in an object.  So the reader already handles your example.  I will make the model clearer.
