### ISSUE TITLE
spatialResolution 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#61]
The MD_Resolution class has not changed from -2 to -1.  However the mdJson has been redesigned to be more intuitive and provide additional options.  Definition: "level of detail expressed as a scale factor, a distance, or angle."  In mdJson 1.0 we did not implement angle

Changes: 
1. "scaleFactor" is an element of type integer.  It was renamed from from"equivalentScale" in mdJson 1.0.  Definition: "level of detail expressed as the scale of a comparable hardcopy map or chart".
2. "measure" is an object of type "measure".  Definition: "a specified distance or angle".  See issue #104..
3. "levelOfDetail" is an element of type string.  Definition: "brief textual description of the spatial resolution of the resource".

``` json
{
   "spatialResolution": [
      {
         "scaleFactor": 45000
      },
      {
         "measure": {
            "see": "measure 2.0"
         }
      },
      {
         "levelOfDetail": ""
      }
   ]
}
```

see ISO XML example spatialReference-3.xml

**Comment by jlblcc** [comment]
Don't need `type` here. I can write the schema to only allow a single type(which I have to do anyway). The property name can then be used to determine the type.

**Comment by stansmith907** [comment]
Not sure what you mean?  Do we create a spatialResolution block in the metadata for each element?  Do we allow multiple types to be set?  Are we setting the impression that all elements need to be supplied by the user?

**Comment by jlblcc** [comment]
It'll look like this:

```json
"spatialResolution": [{
   "scaleFactor": 99999
 }, {
   "measure": {
     "type": "distance",
     "value": 99.9,
     "unitOfMeasure": "unitOfMeasure"
   }
 }, {
   "levelOfDetail": "levelOfDetail"
 }]
```

**Comment by stansmith907** [comment]
Dropped "type".
