### ISSUE TITLE
coverageDescription 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#67]
MD_CoverageDescription is the parent class for MD_AttributeGroup and MD_ImageDescription.  It is also the parent for MI_ImageDescription and MI_CoverageDescription which we are not implementing.  Definition: "Details about the content of a resource."

Changes: none, but some explanation follows...
1. "coverageName" and "coverageDescription are mdJson elements.  We combine these in ISO 19115-n as "{coverageName}; {coverageDescription}" and place the result in ISO's "attributeDescription"  Definition: "description of the attribute described by the measurement value".  

``` json
{
   "coverageDescription": {
      "coverageName": "",
      "coverageDescription": "",
      "processingLevelCode": {
         "see": "identifier 2.0"
      },
      "attributeGroup": [
         {
            "see": "attributeGroup 2.0"
         }
      ],
      "imageDescription": {
            "see": "image 2.0"
      }
   }
}
```

**Comment by stansmith907** [comment]
Yep, my bad.  I do have it as "coverageDescription in my examples.  I changed it above.

**Comment by jlblcc** [comment]
Is _imageDescription_ meant to be an _object_ or _array_? Example conflicts with model above.

**Comment by stansmith907** [comment]
Only one image per coverageDescription.  I'll patch the model.

Also, looks like this was an early model that didn't get it's review update.  "processingLevelCode" should have been "identifier 2.0" not "authority 2.0".  I made that change to the model as well.
