### ISSUE TITLE
attribute 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#68]
attribute is a object of elements belonging to the classes of MD_RangeDimension, MD_SampleDimension, MD_Band, and MI_Band.array.  Which class is instantiated in the writer depends on which elements were populated in the mdJson.    

Changes: changes were discussed in issue #65 (contentInfo 2.0).
1. "units" is required if either "minValue" or "maxValue" are populated.
2. "boundUnits" is required if either "boundMin" or "boundMax" are populated.
3. "sequenceIdentifierType" is required if sequenceIdentifier" is populated.

Definitions: 
- "sequenceIdentifier" is an element of type string.  Definition: "unique name or number that identifies attributes included in the coverage".  Note: "sequenceIdentifier" and "sequenceIdentifierType" are elements in the ISO class MemberName borrowed from another ISO standard.  I flattened the MemberName class into these 2 elements.  This the identifier for the attribute within the resource dataset. 
- "attributeDescription" is a string element inherited from MD_RangeDimension.  Definition: :description of the attribute".
- "sequenceIdentifierType" is an element of type string.  Definition: "type of unique name or number that identifies attributes included in the coverage".  E.g. integer, string.  Note: see note for "sequenceIdentifier" above.
- "attributeIdentifier" is an array of type MD_Identifier.  Definition: "identifiers for each attribute included in the resource.  NOTE These identifiers can be used to provide names for the attribute from a standard set of names."  These are common names by which the attribute may be known along with a link to an external definition and namespace. 
- "minValue" is an element of type real.  Definition: "minimum value of data values in each dimension included in the resource.  NOTE Restricted to UomLength in the MD_Band class."  This would be "boundMin". 
- "maxValue" is an element of type real.  Definition: "maximum value of data values in each dimension included in the resource.  NOTE Restricted to UomLength in the MD_Band class."  This would be "boundMax". 
- "units" is a mdJson element of type string.  The mdTranslator reformats this to MD_UnitsOfMeasure for ISO output.  Definition: "units of data in each dimension included in the resource.  NOTE The type of this is UnitsOfMeasure and that it is restricted to Uom-Length in the MD_Band class."
- "scaleFactor" is an element of type real.  Definition: "scale factor which has been applied to the cell value".
- "offset" is an element of type real.  Definition: "the physical value corresponding to a cell value of zero".
- "meanValue" is an element of type real.  Definition: "mean value of data values of each dimension included in the resource".
- "numberOfValues" is an element of type integer.  Definition: "the number of values used in a thematic-Classification resource.  EXAMPLE The number of classes in a Land Cover Type coverage or the number of cells with data in other types of coverages." 
- "standardDeviation" is an element of type real.  Definition: "standard deviation of data values in each dimension included in the resource". 
- "bitsPerValue" is an element of type integer.  Definition: "maximum number of significant bits in the uncompressed representation for the value in each band of each pixel". 
- "boundMin" is an element of type real.  Definition: "shortest wavelength that the sensor is capable of collecting within a designated band".
- "boundMax" is an element of type real.  Definition: "longest wavelength that the sensor is capable of collecting within a designated band".
- "boundUnits" is an element of type string.  The mdTranslator reformats this to MD_UomLength for ISO output.  Definition: "units in which sensor wavelengths are expressed".
- "peakResponse" is an element of type real.  Definition: "wavelength at which the response is the highest". 
- "toneGradations" is an element of type integer.  Definition: "number of discrete numerical values in the data". 
- "bandBoundaryDefinition" is an element of type MI_BandDefinition (codelist).  Definition: "designation of criterion for defining maximum and minimum wavelengths for a spectral band".
- "nominalSpatialResolution" is an element of type real.  Definition: "smallest distance between which separate points can be distinguished, as specified in instrument design". 
- "transferFunctionType" is an element of type MI_TransferFunctionTypeCode.  Definition: "type of transfer function to be used when scaling a physical value for a given element".
- "transmittedPolarization" is an element of type MI_PolarisationOrientationCode.  Definition: "polarization of the radiation transmitted".
- "detectedPolarization" is an element of type MI_PolarisationOrientationCode.  Definition: "polarization of the radiation detected".

``` json
{
   "attribute": [
      {
         "sequenceIdentifier": "",
         "sequenceIdentifierType": "",
         "attributeDescription": "",
         "attributeIdentifier": [
            {
               "see": "identifier 2.0"
            }
         ],
         "minValue": 0.0,
         "maxValue": 0.0,
         "units": "Distance",
         "scaleFactor": 0,
         "offset": 0,
         "meanValue": 0.0,
         "numberOfValues": 0,
         "standardDeviation": 0.0,
         "bitsPerValue": 0,
         "boundMin": 0.0,
         "boundMax": 0.0,
         "boundUnits": "Distance",
         "peakResponse": 0.0,
         "toneGradations": 0,
         "bandBoundaryDefinition": "MI_BandDefinition",
         "nominalSpatialResolution":  0.0,
         "transferFunctionType": "MI_TransferFunctionTypeCode",
         "transmittedPolarization": "MI_PolarisationOrientationCode",
         "detectedPolarization": "MI_PolarisationOrientationCode"
      }
   ]
}
```

see ISO XML example contentInfo -3.xml

**Comment by jlblcc** [comment]
I assume this shouldn't be here:
`3. "attributeContentType" is a required array of type MD_CoverageContentTypeCode.
`

**Comment by stansmith907** [comment]
True, belongs to "AttributeGroup" #121.  

I removed it from the above model.
