### ISSUE TITLE
keywords 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#71]
"keyword" is essentially unchanged from -2 to -1; however the 2.0 mdJson has been changed to support the mdEditor and maintain a reference to the keyword's location in a supported keyword list.  Also, a new object was added to MD_Keywords class  in -1.

Changes: 
1. "keywordClass" is a new object of type MD_KeywordClass.  I did not add this to mdJson 2.0.  Definition: "association of a MD_Keywords instance with a MD_KeywordClass to provide user-defined categorization of groups of keywords that extend or are orthogonal to the standardized KeywordTypeCodes and are associated with an ontology that allows additional semantic query processing.  NOTE The thesaurus citation specifies a collection of instances from some ontology, but is not an ontology. It might be a list of places that include rivers, mountains, counties and cities. There might be a Laconte county, the city of Laconte, the Laconte River, and Mt. Laconte; when searching it is useful for the user to be able to restrict the search to only rivers."
   - "className" is a required element of type string.  Definition: "character string to label the keyword category in natural language". 
   - "conceptIdentifier" is an element of type URI.  Definition: "URI of concept in the ontology specified 
     by the next element (ontology) and labelled by the previous element (className)". 
   - "ontology" is a required object of type CI_Citation.  Definition: "reference that binds the keyword class to a formal conceptualization of a knowledge domain for use in semantic processing.  NOTE Keywords in the associated MD_Keywords keyword list must be within the scope of this ontology." 
2. "keyword" is an object of type 'keywordObject' (see issue #126).   

``` json
{
  "keyword": [
    {
      "keywords": [
        {
          "see": "keywordObject 2.0"
        }
      ],
      "keywordType": "",
      "thesaurus": {
        "see": "citation 2.0"
      }
    }
  ]
}
```

see ISO XML example keyword -3.xml

**Comment by jlblcc** [comment]
Array property names should be singular, right?

**Comment by stansmith907** [comment]
Should be, but I made an exception so we didn't have keyword in keyword in keyword. But I'm not really resistant to doing that if you want. Up to you.
