### ISSUE TITLE
associatedResource 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#72]
Changes: 
1. The ISO -2 object "aggregateDataSetIdentifier" of type MD_Identifier was removed from -1.  Since we did not support this in mdJson 1.0 there is nothing we need to do.
2. ISO -1 added the "metadataReference" object of type CI_Citation.  This one place we peeked ahead and added this to mdJson for future support for -1, so there is nothing to do. 
3. "associationType" is a required element of type DS_AssociationTypeCode.
4. Because we did not include "aggreageDataSetIdentifier" "resourceCitation"  is required. 
5. "resourceType" is an ADIwg array of type resourceType 2.0 #130.  I also made this element required. 

``` json
{
   "associatedResource": [
      {
         "resourceType": [
            {
               "see": "resourceType 2.0"
            }
         ],
         "associationType": "",
         "initiativeType": "",
         "resourceCitation": {
            "see": "citation 2.0"
         },
         "metadataCitation": {
            "see": "citation 2.0"
         }
      }
   ]
}
```

see ISO XML example associatedResource -3.xml

**Comment by jlblcc** [comment]
Hmmm...it should be _resourceType_ in mdJSON 1.0 as well: http://mdtools.adiwg.org/#viewer-page?v=2-4-0

**Comment by stansmith907** [comment]
**Hmmm...it should be resourceType in mdJSON 1.0 as well:**
And so it was.  The comment in error has been removed.
