### ISSUE TITLE
metadataInfo 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#74]
There are numerous changes to the "metadataInfo" block.  I also the fields marked as deprecated in mdJson 1.0.  There is no ISO definition as these items appear at the root level of the MD_Metadata class.  

Changes: 
1. "metadataCharacterSet" was deprecated in mdJson 1.0 and has been removed.
2. "defaultMetadataLocale" is a new object of type "locale".  Definition: "language and character set used for documenting metadata".  Required if NOT utf-8.  If missing the translator will fill in as utf-8, English US.  
3. "otherMetadataLocale" is an array of "locale" objects.  This was renamed from "metadataLocale" in mdJson 1.0.
4. "metadataDate" is a new array of type CI_Date.  This array replaces the mdJson 1.0 elements "metadataCreationDate" and "metadataLastUpdate".  Definition: "date(s) associated with the metadata. ISO requires a metadata creation date be added to the array, this will be defaulted to now() if an entry is not found. 
5. "metadataOnlineResource" is a new array of type CI_OnlineResource.  This replaces the scalar element "metadataURI.  Definition: "online location where the metadata is available".
6. "alternateMetadataReference" is a new array of type "CI_Citation".  Definition: "reference to alternative metadata, e.g Dublin Core, FGDC, or metadata in a non-ISO standard for the same resource".
7. "metadataContact" is required. 
8. "metadataStatus" is an element of type MD_ProgressCode.  I think this is an ADIwg added element to provide a status of completion for the metadata record.  

``` json
{
   "metadataInfo": {
      "metadataIdentifier": {
         "see": "identifier 2.0"
      },
      "parentMetadata": {
         "see": "citation 2.0"
      },
      "defaultMetadataLocale": {
         "see": "locale 2.0"
      },
      "otherMetadataLocale": [
         {
            "see": "locale 2.0"
         }
      ],
      "metadataContact": [
         {
            "see": "contact 2.0"
         }
      ],
      "metadataDate": [
         {
            "see": "date 2.0"
         }
      ],
      "metadataOnlineResource": [
         {
            "see": "onlineResource 2.0"
         }
      ],
      "metadataMaintenance": {
         "see": "maintenance 2.0"
      },
      "alternateMetadataReference": [
         {
            "see": "citation 2.0"
         }
      ],
      "metadataStatus": "MD_ProgressCode"
   }
}
```

see ISO XML example metadataInfo -3.xml

**Comment by jlblcc** [comment]
Do we need to have "defaultMetadataLocale"? We make at least one locale required. JSON arrays are an ordered set.

**Comment by jlblcc** [comment]
Changes:

- defaultMetadataLocale to metadataLocale
- otherMetadataLocale to additionalMetadataLocale
- otherMetadataDates to metadataDate
- resourceScope to scope
- metadataLinkage to metadataOnlineResource

**Comment by stansmith907** [comment]
I would prefer to keep defaultMetadatLocale rather than metadataLocale.  Otherwise there is no understanding why we have metadataLocale as well as additionalMetadataLocale.  I see 'default' as the explanation.

**Comment by jlblcc** [comment]
Do we need both? See comment [above](https://github.com/adiwg/mdJson-schemas/issues/74#issuecomment-274660387).

**Comment by stansmith907** [comment]
I did see comment above.  Yes, I think so.

**Comment by jlblcc** [comment]
Why? 99% of the time there's only going to be one locale. In the few instances where this is not true, can't we just use the first one (I assume this is due to the -2 writer being limited to one locale?).

**Comment by stansmith907** [comment]
Because if some project is multilingual, or a study in native american languages as one USGS project that asked us about metadata, there is no guarantee they will enter the default language first, or even at all.  And we have no way to resort the list of locales if it was not entered first.  The default locale is required in ISO so we don't wish it to be overlooked, other locales are not reqired.  Unless we want to build a custom control with a radio button for each locale to specify which is default.  Then use that to resort on output to mdJson.  

Also, additionalLocale as opposed to otherLocale does not add anything for me.  In fact it feels less attached to the resource than 'other'.

**Comment by jlblcc** [comment]
As far as the UI, I would implement a "default" button/toggle/whatever regardless of whether we have two objects here or not. Otherwise, you'll need two separate UI controls to support the two objects.

**Comment by stansmith907** [comment]
Yes, two controls are needed, but not a custom control.  They will use the same components we have used everywhere else.  Nothing new, just another element.

**Comment by jlblcc** [comment]
I would implement a custom control for this. Makes it smaller and less confusing.

**Comment by jlblcc** [comment]
Edited the changes, see above.

**Comment by stansmith907** [comment]
The change to otherMetadataDate is also confusing.  Metadata creation date is required so it is separate.  Other dates are not.  Just calling it metadataDate makes one ask why creation date is not also in metadataDate.

**Comment by jlblcc** [comment]
Yeah, I would suggest it should be. :smirk: 

I think _otherMetadataDate_ is misleading, eye of the beholder and all that... I will change it back if you want.

**Comment by stansmith907** [comment]
I do strongly suggest we leave this as "defaultLocale" and "otherLocale".  

1. "defaultLocale" is require, "otherLoale" is optional.
2. There will complications in determining which locale is default in the mdEditor and other generators of mdJson if it is not specifically marked.  
3. The two elements have different definitions.
4. The two elements only share the same object type.  Similar to "resourceCitation" and "metadataCitation" in "associatedResource".  We would not put these in an array and loose track of which is which.
5. And this is a very big change to the reader/writer tests since it is a required element at the highest level it will impact every test I have.  Not fun.

**Comment by jlblcc** [comment]
I didn't change those. The changes I did make are noted in my previous comment.

**Comment by stansmith907** [comment]
Sorry, lots of comments above.  Refresh my memory.

**Comment by jlblcc** [comment]
This is what I changed:
- otherMetadataDates to metadataDate
- resourceScope to scope
- metadataLinkage to metadataOnlineResource

Do we need to have metadataCreationDate separate? Could we just have a metadataDate entry with `"dateType" = "creation"`? Right now the schema _requires_ metadataCreationDate, but as you've stated in the text we plan to provide defaults in the editor and translator. So should it really be required? I can make metadataDate with the **_first_** array member required with `"dateType" = "creation"`. ~~Alternatively, I can make at least one date with the dateType=creation required regardless of order - the schema for this situation is kinda weird in the current json-schema spec.~~

**Comment by stansmith907** [comment]
It is possible to include creation date in "metadataDate" but we have the same problem as locale.  "metadataCreationDate" is required the other dates are optional, plus we have no simple means of informing/enforcing entry of "metadataCreationDate" without making it a separate element.  We can build custom controls for mdEditor, but that doesn't help when metadata is generated from other systems. 

Also, if "metadataCreationDate" exists "otherMetadataDate" is more informative than "metadataDate". 

Renaming of "resourceScope" and "metadataLinkage" are good for me.

**Comment by jlblcc** [comment]
I can enforce the creation date rule as stated above. It will be documented in mdTools. Otherwise, I vote that we relax the schema and just make it a "recommended" field, esp given the fact that we're going to add defaults in implementation. I think this is somewhat different than the "locale" issue, since we're talking about requiring a specific value I can actually write the schema to **require** that to be the first array element. Also, what do you think about amending the metadataDate array to contain objects with a description and date as properties? Or we could add a description property to the main date object.

**Comment by stansmith907** [comment]
Still easy to miss the hints.  

However, I do default the empty/missing "metadataCreationDate" to now().  And the good news is I did not include "metadataCreationDate" in the writer test data files, so now massive changes would be need to eliminate the element.  I feel the intent is cleaner with "metadataCreationDate" and "otherMetadataDates", but if it is really bugging you, we can change it.

**Comment by jlblcc** [comment]
Why don't we discuss with the group tomorrow? What do you think about adding the description?

**Comment by stansmith907** [comment]
"date" already has "dateType" which is kind of a description.  Are you thinking to add "description" in addition to "dateType"?

**Comment by jlblcc** [comment]
Yep, for comments/explanation. That's something we capture here that I have nowhere to put in the mdJSON.

**Comment by stansmith907** [comment]
No problem and no output to ISO.

**Comment by stansmith907** [comment]
Removed 'metadataCreationDate'
Renamed 'otherMetadataDates' to 'metadataDate'

**Comment by stansmith907** [comment]
Just to clarify, looking at the code again after a long while I rediscovered the ISO element 'dateStamp'  This is the date the metadata record was generated and is defaulted to now() in the reader.  DateType = 'creation' then would likely be the date the metadata record was authored, thus we should NOT be defaulting this date.  I'll just plug it as nilReason = 'missing' if it in face is.

**Comment by stansmith907** [comment]
Recap, 
otherMetadataDates changed to metadataDate
metadataLinkage changed to metadataOnlineResource
defaultLocale not changed
otherLocale not changed

Can we leave resourceScope as resourceScope?  Reason this is sitting in metadataInfo section but refers to the resource, not the metadata.

**Comment by jlblcc** [comment]
So we have both resourceType and scope, Are these the same thing??? That's confusing. The definition for scope in metadataInfo is "The scope/type of resource for which metadata is provided." I read that as metadata scope, which, in theory, could be different from resourceType. Again, confusing.

Maybe we should just have one or the other. If we keep scope, what about moving it to resourceInfo? Or maybe we should move it there even if we keep both. If it's, in fact, referring to the resource.

**Comment by stansmith907** [comment]
Good catch. 

After some very brief research resourceType was our invention for -2 metadata.  Because we did not implement hierarchyLevel in metadataInfo section.  We stuck it in resourceInfo because that made more sence.

In ISO -1 hierarchyLevel was replaced with MD_Scope in the metadataInfo section.  So, I added it.  It is just an expansion of our resourceType.  I agree that it would make sense to move it into resourceInfo and strike resourceType.  

We also use resourceType in associatedResource and additionalDocumentation.  Change all three?

**Comment by jlblcc** [comment]
One problem I foresee is having resourceType/scope as an array. Seems like maybe this should just be a single object. Otherwise, I don't know how you'd implement automated processing reliably?

**Comment by jlblcc** [comment]
Confirm we're dropping scope from the object in favor of resourceType? resourceType will become an array of objects equivalent to MD_MetadataScope.

**Comment by stansmith907** [comment]
Confirmed, although I don't think we ever added scope to resourceInfo, just discussed the merits.

**Comment by stansmith907** [comment]
Removed "resourceScope", ISO 19115-2 "hierarchy" can be created from "resourceInfo < resourceType".
