### ISSUE TITLE
gridRepresentation 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#77]
"gridRepresentation" is one of four possible forms of spatial representation.  See "spatialRepresentation (issue #60) for more information.

Changes: 
1. The "gridRepresentation" object was renamed from "gridInfo" in mdJson 1.0.

``` json
{
   "gridRepresentation": [
      {
         "numberOfDimensions": 0,
         "dimension": [
            {
               "see": "dimension 2.0"
            }
         ],
         "cellGeometry": "MD_CellGeometryCode",
         "transformationParameterAvailability": false
      }
   ]
}
```

see ISO XML example spatialRepresentation -3.xml

**Comment by jlblcc** [comment]
We're renaming "transformationParameterAvailability" to "transformParamsAvailability"?

**Comment by jlblcc** [comment]
I used "transformationParameterAvailability", the same as 1.0.

**Comment by stansmith907** [comment]
Sounds good.  Matches other spatial representation patterns.  I will change to same.  I changed the above model.
