### ISSUE TITLE
georectifiedRepresentation 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#79]
"georectifiedRepresentation" is one of four possible forms of spatial representation.  See "spatialRepresentation (issue #60) for more information.  

Changes:
1.  "georectifiedRepresentation" is an object sub-type of MD_GridRepresentation.  Definition: "grid whose cells are regularly spaced in a geographic (i.e. lat/long) or map coordinate system defined in the SpatialReferencing System (SRS) so that any cell in the grid can be geolocated given its grid coordinates and the grid origin, cell spacing, and orientation."
   - "gridRepresentation" is a required object.
   - "checkPointAvailability" is a required Boolean element.  Definition: "indication of whether or not geographic position points are available to test the accuracy of the georeferenced grid data."
   - "checkPointDescription" is a string element.  This element is required if "checkPointAvailability" is true.  Definition: "description of geographic positions points used to test the accuracy of the georeferenced grid data."
   - "cornerPoints" is a required array of 2 or 4 "coordinate" points objects.  Definition: "earth location in the coordinate system defined by the Spatial Reference System and the grid coordinate of the cells at opposite ends of grid coverage along two diagonals in the grid spatial dimensions.  Note: There are four corner points in a georectified grid; at least two corner points along one diagonal are required.  The first corner point corresponds to the origin of the grid."
   - "centerPoint" is an object of type coordinate point object.  Definition: "earth location in the coordinate system defined by the Spatial Reference System and the grid coordinate of the cell halfway between opposite ends of the grid in the spatial dimensions."
   - "pointInPixel" is a required element of type MD_PixelOrientationCode.  Definition: "point in a pixel corresponding to the Earth location of the pixel."
   - "transformatioinDimensionDescription" is a string element.  Definition: "general description of the transformation." 
   - "transformationDimensionMapping" is a string element.  Defnintion: " information about which grid axes are the spatial (map) axes."

``` json
{
   "georectifiedRepresentation": {
      "gridRepresentation": {
         "see": "gridRepresentation 2.0"
      },
      "checkPointAvailable": true,
      "checkPointDescription": "",
      "cornerPoints": [
         [0.0, 0.0],
         [0.0, 0.0],
         [0.0, 0.0],
         [0.0, 0.0]
      ],
      "centerPoint": [0.0, 0.0],
      "pointInPixel": "MD_PixelOrientationCode",
      "transformationDimensionDescription": "",
      "transformationDimensionMapping": ""
   }
}
```

see ISO XML example spatialRepresentation -3.xml

**Comment by jlblcc** [comment]
Just curious, where is the SRS defined? In resourceInfo? That's an array. So, how do we know which SRS is used here? Looks like the same problem exists in ISO. Am I missing something?

**Comment by jlblcc** [comment]
I'm assuming "checkPointAvailability" should be "checkPointAvailable", as shown in the example.

**Comment by stansmith907** [comment]
Sorry you asked.  In ISO spatial representation types there are a number of Boolean elements that end in "Availability".  In all cases except "checkPointAvailable" I used the ISO name.  However, on further thought"...Availability" => true seems somewhat ambiguous.  I do like "..Available" => true better.  

If we go this way we also should change 
1. "grid" > "transformParamsAvailability"
2. "georectified" > "checkPointAvailable" (this issue)
3. "georeferenceable" > "controlPointAvailability" / "orientationParameterAvailability"

Further, "...Available" matches what mdJson and ISO did in "coverageDescription" > "image".

This is just name changing and not a significant impact on the reader code.  I'm okay with changing if you are.

**Comment by jlblcc** [comment]
I'm not _necessarily_ advocating for changing everywhere, although I think "available" makes more sense. I was mainly asking due to the discrepancy in the text explanation and the example. So, should we change it everywhere?

**Comment by stansmith907** [comment]
I'm up for the universal change.  It's not too much of an impact on this end.  You?

**Comment by jlblcc** [comment]
Not a problem here, just a few property names. I updated your list with checkboxes.
