### ISSUE TITLE
resourceInfo 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#80]
"resourceInfo" is the mdJson object containing descriptive information about the data resource.  The order of some elements and objects was changed. 

Changes:
1. "resourceType" is a required array of mdJson object type "resourceType" and is used by ISO -2 for hierarchyLevel and hierarchyLevelName, and ISO -1 for metadataScope both in the metadataInfo section of record. 
2. "shortAbstract" is a mdJson element of type string and is not used by ISO.  Use is intended for website presentation and lookup.
3. "timePeriod": is a mdJson element of type timePeriod and is not used by ISO.  Use is intended primarily by project metadata records.
4. "hasMapLocation" is a mdJson 1.0 element and was removed from mdJson 2.0.
5. "hasDataAvailable" is a mdJson 1.0 element and was removed from mdJson 2.0.
6. "language" was deprecated in mdJson 1.0 in favor of "defaultResourceLocale" as was removed from mdJson 2.0.
7. "characterSet" was deprecated in mdJson 1.0 in favor of "defaultResourceLocale" as was removed from mdJson 2.0.
8. "temporalResolution" is a new mdJson 2.0 object of type duration (see issue #82).  The result will populate an ISO element of type TM_PeriodDuration.  Definition: "smallest resolvable temporal period in a resource".
9. "coverageDescription" is a array of MD_CoverageDescription objects.  Renamed from "coverageInfo" in mdJson 1.0.
10. "spatialRepresentationType" is an element of type MD_SpatialRepresentationTypeCode.  It was renamed from "spatialRepresentation" in mdJson 1.0.
11. "spatialRepresentation" is a mdJson object containing the 4 ISO MD_SpatialRepresentation sub-types.  The object was renamed from "gridInfo" in mdJson 1.0.  
12. "dataQualityInfo" was moved out of "resourceInfo" and renamed "resourceLineage". 
13. "resourceUsage" was renamed in mdJson from "resourceSpecificUsage".
14. "defaultResourceLocale" is a new ISO object of type PT_Locale.  It replaces "language" and "characterSet".  Definition: "language and character set used within  the resource". 
15. "otherResourceLocale" is a new array of type PT_Locale.  Definition: "alternate localised language(s) and character set (s) used within the resource".
16. "resourceFormat" was renamed in mdJson 2.0 from "resourceNativeFormat".
17. "resourceType, "citation", "abstract", "pointOfContact", "status", and "defaultResourceLocale" are all required elements.
18. "status" is a required array of type "MD_ProgressCode".

``` json
{
   "resourceInfo": {
      "resourceType": [
         {
            "see": "resourceType 2.0"
         }
      ],
      "citation": {
         "see": "citation 2.0"
      },
      "abstract": "",
      "shortAbstract": "",
      "purpose": "",
      "timePeriod": {
         "see": "timePeriod 2.0"
      },
      "credits": [""],
      "status": ["MD_ProgressCode"],
      "topicCategory": ["MD_TopicCategoryCode"],
      "pointOfContact": [
         {
            "see": "responsibility 2.0"
         }
      ],
      "spatialReferenceSystem": [
         {
            "see": "spatialReference 2.0"
         }
      ],
      "spatialRepresentationType": ["MD_SpatialRepresentationTypeCode"],
      "spatialRepresentation": [
         {
            "see": "spatialRepresentation 2.0"
         }
      ],
      "spatialResolution": [
         {
            "see": "spatialResolution 2.0"
         }
      ],
      "temporalResolution": [
         {
            "see": "duration 2.0"
         }
      ],
      "extent": [
         {
            "see": "extent 2.0"
         }
      ],
      "coverageDescription": [
         {
            "see": "coverageDescription 2.0"
         }
      ],
      "taxonomy": {
         "see": "taxonomy 2.0"
      },
      "graphicOverview": [
         {
            "see": "graphic 2.0"
         }
      ],
      "resourceFormat": [
         {
            "see": "format 2.0"
         }
      ],
      "keyword": [
         {
            "see": "keyword 2.0"
         }
      ],
      "resourceUsage": [
         {
            "see": "usage 2.0"
         }
      ],
      "constraint": [
         {
            "see": "constraint 2.0"
         }
      ],
      "defaultResourceLocale": {
         "see": "locale 2.0"
      },
      "otherResourceLocale": [
         {
            "see": "locale 2.0"
         }
      ],
      "resourceMaintenance": [
         {
            "see": "maintenance 2.0"
         }
      ],
      "environmentDescription": "",
      "supplementalInfo": ""
   }
}
```

no ISO XML example

**Comment by jlblcc** [comment]
I think the first three descriptions were mistakenly duplicated?

**Comment by stansmith907** [comment]
You are correct.  The issue has been updated.

**Comment by jlblcc** [comment]
Are "coverageDescription" and "contentInfo" referring to the same object? Which name are we using?

**Comment by stansmith907** [comment]
In ISO (where the terms originate) "contentInfo" is the outer container.  In -1 it contains "coverageDescription", "featureCatalogueDescription", and "featureCatalogue" (ISO 19110).  So, in mdJson we collect "dataDictionary" and 'coverageDescription" separately and then write them out under the proper container object "contentInfo".

**Comment by jlblcc** [comment]
Understood. However, the example above uses "coverageDescription", but it's called "contentInfo" in #67. Which property name should I use in resourceInfo?

**Comment by stansmith907** [comment]
Yep, my bad.  I changed it on #67.  I did have it as "coverageDescription" in my examples.

**Comment by jlblcc** [comment]
I see ISO mage _status_ an array. That doesn't make much sense to me - unless we're considering this an ___ordered___ array per the JSON spec. Otherwise, how do we know the current status without a date?

**Comment by jlblcc** [comment]
Rename "credits" to "credit"

**Comment by jlblcc** [comment]
Confirm that we are changing resourceType to an array of resourceType objects, see  #130.
