### ISSUE TITLE
duration 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#82]
Duration is a mdJson 2.0 object for collecting information about a duration or period of time.  The values can be any positive integer.  E.g. 72 (72 hours) or 18 (18 months) are also valid entries.  Multiple elements are also valid such as 1 year, 6 month, and 3 days.  

``` json
{
   "years": 0,
   "months": 0,
   "days": 0,
   "hours": 0,
   "minutes": 0,
   "seconds": 0
}
```

no ISO XML example

**Comment by jlblcc** [comment]
So the value for hours can be "72H"? So either an integer or a string are valid?

**Comment by stansmith907** [comment]
Sorry!  Input to each element is an integer.  Input would be "hours": 72, output in ISO would be 72H.
