### ISSUE TITLE
entityAttribute 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#84]
The schemas for mdJson "dataDictionary" and ISO 19110 have not changed.  The mdJson schema for "attribute" is included here for review and comment.

Changes: none

``` json
{
   "attribute": [
      {
         "commonName": "",
         "codeName": "",
         "alias": [""],
         "definition": "",
         "dataType": "",
         "allowNull": true,
         "allowMany": false,
         "units": "",
         "domainId": "",
         "minValue": "",
         "maxValue": ""
      }
   ]
}
```

see ISO XML example ISO 19110.xml

**Comment by stansmith907** [comment]
I added "allowMany" to the entityAttribute schema to support ISO's upper limit cardinality.  A value of *false* (default) is max cardinality of 1 and value of *true* is max cardinality of max integer represented in our ISO output as 99999.

I am tentative about adding the element.  It does not play well with descriptions of normalized databases but can be used in describing object models, JSON, some spreadsheet designs, and possibly no-SQL databases.  

The "allowMany" element would likely never be used in a normalized database since repeating elements (*the many*) would have been split off into a separate table and linked by a foreign key both of which can be expressed by the mdJson schema.  

I'm happy to take the element out if requested.

**Comment by jlblcc** [comment]
@stansmith907, what's the definition for allowMany?

**Comment by stansmith907** [comment]
It's maximum cardinality.  'false' is max cardinality of 1; 'true' max cardinality of many.  However, 'many' in ISO 19110 is translated to 99999 by me since 19110 requires an integer for max cardinality.
