### ISSUE TITLE
domain 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#88]
The schemas fpr mdJson "dataDictionary" and ISO 19110 have not changed.  The mdJson schema for "domain" is included here for review and comment.

Changes: none

``` json
{
   "domain": [
      {
         "domainId": "",
         "commonName": "",
         "codeName": "",
         "description": "",
         "domainItem": [
            {
               "see": "domainItem 2.0"
            }
         ]
      }
   ]
}
```

see ISO XML example ISO 19110.xml

**Comment by jlblcc** [comment]
member was changed to domainItem.
