### ISSUE TITLE
timePeriod 2.0

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdJson-schemas#92]
"timePeriod" is a GML object not ISO.  Documentation for this element was taken from  the ISO -3 XSD, the object is not covered in ISO documents.    

Changes: 
1. "identifier" is an array of type identifier.  See definition below.  
2. "names" is a new array of name objects.  See definition below.
3. "relatedTime" is a new array of type timeInstant, timePeriod, timeEdge, or timeNode.  See definition below. 
4. "startDateTime" is a dateTime element.  startdateTime was renamed from "beginPosition" in mdJson 1.0. 
5. "endDateTime" is a dateTime element.  endDateTime was renamed from "endPosition" in mdJson 1.0.
6. "timeInterval" is a new element of type timeInterval.  See issue #103 and definition below.
7. "duration" is a new element of type duration.  See definition below.

Definitions: 
- "id": All GML timeInstant(s) required an alphanumeric ID that must start with a letter and contain no special characters, including spaces.  If the ID is not provided the mdTranslator will generate one. 
- "description": A character string description of the timeInstant.
- "identifier": A special identifier is assigned to an object by the maintaining authority with the intention that is used in references to the object.  That identifier is usually unique either globally or within an application domain. 
- "periodName": Is an array of names.  The gml:name property provides a label or identifier for the object, commonly a described name.  In gml the authority for a name is indicated by the value of its codeSpace (optional).  The names need not be unique, name + namespace should be unique.  However codeSpace is not supported in the ISO XSD implementation.  Therefore it was not added to the mdJson.
- "relatedTime": gml:RelatedTime provides a content model for indicating the relative position of an arbitrary member of the substitution group whose head is gml:AbstractTimePrimitive.  RelatedTime is a "timeInstant", "timePeriod", "timeEdge", or "timeNode".  Not implemented.
- "startDateTime": dateTime of the start of the time period. 
- "endDateTime": dateTime of the end of the time period. 
- "timeInterval": Frequency between time events based on floating point values for temporal length.
- "duration": Length of time between measurements.
- "metaDataProperty" No definition provided.  Any ISO or GML class can be placed here. 
- "descriptionReference" gml:ReferenceType is intended to be used in application schemas directly, if a property element shall use a "by-reference-only" encoding.  The value of this property is a remote text description of the object.  Use the xlink:href object. 

``` json
{
   "timePeriod": {
      "id": "",
      "description": "",
      "identifier": {
         "see": "identifier 2.0"
      },
      "periodName": [""],
      "startDateTime": "YYYY-MM-DDTHH:MM:SS.S+HH:MM",
      "endDateTime": "YYYY-MM-DDTHH:MM:SS.S+HH:MM",
      "timeInterval": {
         "see": "timeInterval 2.0"
      },
      "duration": {
         "see": "duration 2.0"
      }
   }
}
```

see ISO XML example temporalExtent -3.xml

Add the following elements to mdJson 2.0....
- [ ] metaDataProperty
- [ ] descriptionReference
- [x] id
- [x] description
- [x] gmlIdentifier
- [x] periodName[ ]
- [ ] relatedTime [ ]
- [x] timeInterval 
- [x] duration

**Comment by jlblcc** [comment]
So was "relatedTime"  implemented?

**Comment by stansmith907** [comment]
"relatedTime" was not implemented.  Do you see a need?  It is just temporalExtent in timePeriod and timeInstant.  

"duration" also was not implemented but we could.  See a need?  "timePeriod" may specify either "timeInterval" or "duration", but not both.

**Comment by stansmith907** [comment]
I didn't implement duration, just timeInterval.  These are mutually exclusive in any timePeriod object.  Since it seems you added it to the schema should I add it to the reader?

**Comment by jlblcc** [comment]
Are we using duration anywhere else outside of timePeriod? I guess I'll need to adjust the schema to only allow one or the other. Can duration be used to document things like repeated measures?

**Comment by stansmith907** [comment]
Duration is used in other places.  I think timeInterval better documents repeated events, but I expect there are cases duration would be more appropriate.  No problem for me to add it in here in the reader.  

I wish we could have both in ISO.  Then a time period of say 5 seconds on each hour could be documented.  I don't see why we can't leave both in the mdJson and then I can just default to timeInterval in the ISO if both are present.  

Lucky you, no changes to the schema!

**Comment by jlblcc** [comment]
Sounds good I will leave as is.
